apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: roon-extension-alarm-clock
  name: roon-extension-alarm-clock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roon-extension-alarm-clock
  strategy: {}
  template:
    metadata:
      labels:
        app: roon-extension-alarm-clock
    spec:
      hostNetwork: true
      containers:
      - image: theappgineer/roon-extension-alarm-clock
        name: roon-extension-alarm-clock
        env:
        - name: TZ
          value: Europe/Copenhagen
        resources: {}
        volumeMounts:
          - name: config-volume
            mountPath: /usr/src/app/config.json
            subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: alarm-clock-config
status: {}
