apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: roon-extension-cd-ripper
  name: roon-extension-cd-ripper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roon-extension-cd-ripper
  strategy: {}
  template:
    metadata:
      labels:
        app: roon-extension-cd-ripper
    spec:
      hostNetwork: true
      containers:
      - image: theappgineer/roon-extension-cd-ripper
        name: roon-extension-cd-ripper
        securityContext:
          privileged: true
        env:
        - name: TZ
          value: Europe/Copenhagen
        resources: {}
        volumeMounts:
          #- name: config-volume
          #  mountPath: /usr/src/app/config.json
          #  subPath: config.json
          #- name: cdrom
          #  mountPath: /dev/cdrom
          - mountPath: /music
            name: music                                                                                                                                                                                                                    
          - name: whipper-config
            mountPath: /root/.config/whipper
      initContainers:
      - image: theappgineer/roon-extension-cd-ripper
        name: create-cdrom-symlink
        command:
          - sh
          - '-ec'
          - >-
            ln -sf /dev/sr0 /dev/cdrom
      volumes:
        - name: config-volume
          configMap:
            name: cd-ripper-config
        - name: whipper-config
          configMap:
            name: whipper-config
        - name: cdrom
          hostPath:
            path: /dev/cdrom
        - name: music
          persistentVolumeClaim:
            claimName: roon-music
      nodeSelector:
        feature.node.kubernetes.io/usb-08_05ac_1500.present: 'true'
status: {}
