---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: roon-release
  namespace: default
spec:
  releaseName: roon
  chart:
    spec:
      chart: roon
      sourceRef:
        kind: GitRepository
        name: roon-repo
  interval: 10m
