apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: roon-release
  namespace: default
spec:
  releaseName: roon
  chart:
    spec:
      chart: roon
      sourceRef:
        kind: GitRepository
        name: roon-repo
  interval: 10m
  values:
    image:
      tag: 2.0.1392 # {"$imagepolicy": "flux-system:roon:tag"}
      pullPolicy: Always
    persistence:
      config:
        enabled: true
        mountPath: /var/roon/
        size: 5Gi
        storageClass: "longhorn"
        retain: true
        accessMode: "ReadWriteOnce"
      music:
        enabled: true
        size: 350Gi
        storageClass: "longhorn"
        retain: true
        accessMode: "ReadWriteOnce"
      backups:
        enabled: true
        size: 20Gi
        storageClass: "longhorn"
        retain: true
        accessMode: "ReadWriteOnce"
    service:
      main:
        # -- Enables or disables the service
        enabled: true

        # -- Set the service type
        type: LoadBalancer

        ports: [9003]
