apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: roon-release
  namespace: default
spec:
  releaseName: roon
  chart:
    spec:
      chart: roon
      sourceRef:
        kind: GitRepository
        name: roon-repo
  interval: 10m
  values:
    image:
      tag: 2.0.1528 # {"$imagepolicy": "flux-system:roon:tag"}
      pullPolicy: Always
    persistence:
      config:
        enabled: true
        mountPath: /var/roon/
        size: 6Gi
        storageClass: "longhorn"
        retain: true
        accessMode: "ReadWriteOnce"
      music:
        enabled: true
        size: 350Gi
        storageClass: "longhorn"
        retain: true
        accessMode: "ReadWriteOnce"
      backups:
        enabled: true
        size: 20Gi
        storageClass: "longhorn"
        retain: true
        accessMode: "ReadWriteOnce"
    nodeSelector:
      kubernetes.io/hostname: 'minis-7373'
