---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: roon-release
  namespace: default
spec:
  releaseName: roon
  chart:
    spec:
      chart: roon
      sourceRef:
        kind: GitRepository
        name: roon-repo
  interval: 10m
  values:
    image:
      pullPolicy: Always
    persistence:
      config:
        enabled: true
        mountPath: /var/roon/
        size: 5Gi
        storageClass: "longhorn"
        retain: true
        accessMode: "ReadWriteOnce"
      music:
        enabled: true
        size: 350Gi
        storageClass: "longhorn"
        retain: true
        accessMode: "ReadOnlyMany"
        readOnly: true
      backups:
        enabled: true
        size: 20Gi
        storageClass: "longhorn"
        retain: true
        accessMode: "ReadWriteOnce"
