apiVersion: v1
kind: Secret
metadata:
    name: samba-users
    namespace: default
type: Opaque
stringData:
    samba-users: ENC[AES256_GCM,data:ywh2A/vrQoamnF9vudfOfGYJ8Z9/JF0YESpR5T4QkfIyEYDNtTJYArL9w1Py+vIZXbAPZWm6BwZKoFP8MwA1JNbDcYHi4SFWK9V+t+kxB614xhgWiSHrQES0wRuJZNaWO5RDCofT21dqT0s0CxkGmwrruvUwXZcS9Lmgq06ELSBlcbqcZaa2dKa/rkucm13Lt9YT4VbR2x3FW8zQCW1o3tE7,iv:GFgzNeUQ2tb68Pm7YUU7867RcwzI8PIUsh94vRWXSDg=,tag:uhUPP054LJYYrGXOLEzt4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOERZOUhMSW82ZGxpYWJ6
            NnhBYThrVGdyaWhhQWlyb3RMd3ZabUpHUFg4Ci9OZHFwdFpZMldUYmFqa3BVNlkz
            SUZwZU1uQjRmOWU0L09MbXRoU3NxNUEKLS0tIE0rdU1Rdi9GNnB0dUZoL3FJNGcv
            dGdJdmtCM0dPM2tHd0JrTTdDWENGMzQK5igdmgnkE+oG+FUCEykeVuOYNHCNie8l
            XloY2mFEdXVoHOSNxfzDLkyec6g7Pxv5dTnT/I1ELKq5bmqpehtaiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T08:43:32Z"
    mac: ENC[AES256_GCM,data:FZl+nD/JhO5IYUYhGF0ILjc0adCZwtN/770G0xlCnh6kbXsFXGxdbRHHSQMvvVOFkvO8OQqXwku0yoxPNd8McXvQ852QphtqU4N2z65eOGrR1FiZvwlCiTx3oGUovvXaU/6cEWm/Dk27fVXsCNOheG88P9IHyFUi2sfmAazGv3s=,iv:L2jHuJk6VqLvJ+8RnlpS0prxpKj+iu3exJWQDtv+cmY=,tag:MFZBP+AP4qfgcuQl9FuC2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
    name: samba-users
    namespace: default
spec:
    mode: user
    users:
        secret: samba-users
        key: samba-users
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOERZOUhMSW82ZGxpYWJ6
            NnhBYThrVGdyaWhhQWlyb3RMd3ZabUpHUFg4Ci9OZHFwdFpZMldUYmFqa3BVNlkz
            SUZwZU1uQjRmOWU0L09MbXRoU3NxNUEKLS0tIE0rdU1Rdi9GNnB0dUZoL3FJNGcv
            dGdJdmtCM0dPM2tHd0JrTTdDWENGMzQK5igdmgnkE+oG+FUCEykeVuOYNHCNie8l
            XloY2mFEdXVoHOSNxfzDLkyec6g7Pxv5dTnT/I1ELKq5bmqpehtaiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T08:43:32Z"
    mac: ENC[AES256_GCM,data:FZl+nD/JhO5IYUYhGF0ILjc0adCZwtN/770G0xlCnh6kbXsFXGxdbRHHSQMvvVOFkvO8OQqXwku0yoxPNd8McXvQ852QphtqU4N2z65eOGrR1FiZvwlCiTx3oGUovvXaU/6cEWm/Dk27fVXsCNOheG88P9IHyFUi2sfmAazGv3s=,iv:L2jHuJk6VqLvJ+8RnlpS0prxpKj+iu3exJWQDtv+cmY=,tag:MFZBP+AP4qfgcuQl9FuC2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbCommonConfig
metadata:
    name: music
    namespace: default
spec:
    network:
        publish: external
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOERZOUhMSW82ZGxpYWJ6
            NnhBYThrVGdyaWhhQWlyb3RMd3ZabUpHUFg4Ci9OZHFwdFpZMldUYmFqa3BVNlkz
            SUZwZU1uQjRmOWU0L09MbXRoU3NxNUEKLS0tIE0rdU1Rdi9GNnB0dUZoL3FJNGcv
            dGdJdmtCM0dPM2tHd0JrTTdDWENGMzQK5igdmgnkE+oG+FUCEykeVuOYNHCNie8l
            XloY2mFEdXVoHOSNxfzDLkyec6g7Pxv5dTnT/I1ELKq5bmqpehtaiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T08:43:32Z"
    mac: ENC[AES256_GCM,data:FZl+nD/JhO5IYUYhGF0ILjc0adCZwtN/770G0xlCnh6kbXsFXGxdbRHHSQMvvVOFkvO8OQqXwku0yoxPNd8McXvQ852QphtqU4N2z65eOGrR1FiZvwlCiTx3oGUovvXaU/6cEWm/Dk27fVXsCNOheG88P9IHyFUi2sfmAazGv3s=,iv:L2jHuJk6VqLvJ+8RnlpS0prxpKj+iu3exJWQDtv+cmY=,tag:MFZBP+AP4qfgcuQl9FuC2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: music
    namespace: default
spec:
    securityConfig: samba-users
    commonConfig: music
    storage:
        pvc:
            name: roon-music
    readOnly: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOERZOUhMSW82ZGxpYWJ6
            NnhBYThrVGdyaWhhQWlyb3RMd3ZabUpHUFg4Ci9OZHFwdFpZMldUYmFqa3BVNlkz
            SUZwZU1uQjRmOWU0L09MbXRoU3NxNUEKLS0tIE0rdU1Rdi9GNnB0dUZoL3FJNGcv
            dGdJdmtCM0dPM2tHd0JrTTdDWENGMzQK5igdmgnkE+oG+FUCEykeVuOYNHCNie8l
            XloY2mFEdXVoHOSNxfzDLkyec6g7Pxv5dTnT/I1ELKq5bmqpehtaiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T08:43:32Z"
    mac: ENC[AES256_GCM,data:FZl+nD/JhO5IYUYhGF0ILjc0adCZwtN/770G0xlCnh6kbXsFXGxdbRHHSQMvvVOFkvO8OQqXwku0yoxPNd8McXvQ852QphtqU4N2z65eOGrR1FiZvwlCiTx3oGUovvXaU/6cEWm/Dk27fVXsCNOheG88P9IHyFUi2sfmAazGv3s=,iv:L2jHuJk6VqLvJ+8RnlpS0prxpKj+iu3exJWQDtv+cmY=,tag:MFZBP+AP4qfgcuQl9FuC2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
