apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbCommonConfig
metadata:
  name: music
  namespace: default
spec:
  network:
    publish: external
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
  name: music
  namespace: default
spec:
  commonConfig: music
  storage:
    pvc:
      name: roon-music
  readOnly: false
