apiVersion: v1
kind: Secret
metadata:
    name: musicusers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:YebLAmN8GkzCjE3t6ZSMQoEZZYwZCFJvmZrEQWJ1flViIaA4Ibmmstm+kqnmb/G7/hzp6BrCVgNti3KZWCLbok0TRgzGiCAC55EFZ/csEZJOkTtiy+BUjVs6EI3KpLp27wayR2YtADwB9skkuKm9ZxXQn6znlAIPZ8Ee10Of9MSVNu5vTzXvWhou7D4Cn7TEMOQTXg47kg2R8A==,iv:e3MZWEiS/OCTyHV8z3QzHzT3kC14taafGwNPz5+AQTQ=,tag:0vcAr/faGjQyz7L5vTvliQ==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRGo0bjZhMFgvNk4ydWV3
            elRxOWppL2JRTWRJVC94NG80Ti9XK01YMFh3CkZPeE1zTDVPUFV2UWZDUC9JWHRv
            M25hWkYzd1FDY00zUzRmUjVUL2s5MzAKLS0tIFViSlROZzRvazZLSWE4cHNsZ3Rl
            QjVQMFMwcHFVOUREeGFaemRHMjB6WFkKP1enPbuv2RGEHOmgKyGPl+lOf1bJtwr+
            iCjVcVIYRiMz1ROMQKgSQRmhx0zaufgn6hNsXTqjQ2G19AFfzGM+Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-27T16:13:35Z"
    mac: ENC[AES256_GCM,data:VLY4h80PBo6JwcScSXGKILsXEXgUs2ifVBgBhf4GfHh4A+IDkkCW/2m494bgj89k/d210x1L3zN3qJwSWMza5yqM66XXIA1t9YMO89fq3eNphNX9J7yA+g9ZMS8UvrbiZTtdMzi/XGyU1ziG+QIjQX2NqYCSyqWCfClw/L7x7UQ=,iv:8ufyBREc5Y+K4infXOORz1tDJrc3xVIQ5AKOTJn01vg=,tag:OdNVvUwt2y9ku4j6IVCVFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
    name: musicusers
    namespace: default
spec:
    mode: user
    users:
        secret: musicusers
        key: demousers
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRGo0bjZhMFgvNk4ydWV3
            elRxOWppL2JRTWRJVC94NG80Ti9XK01YMFh3CkZPeE1zTDVPUFV2UWZDUC9JWHRv
            M25hWkYzd1FDY00zUzRmUjVUL2s5MzAKLS0tIFViSlROZzRvazZLSWE4cHNsZ3Rl
            QjVQMFMwcHFVOUREeGFaemRHMjB6WFkKP1enPbuv2RGEHOmgKyGPl+lOf1bJtwr+
            iCjVcVIYRiMz1ROMQKgSQRmhx0zaufgn6hNsXTqjQ2G19AFfzGM+Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-27T16:13:35Z"
    mac: ENC[AES256_GCM,data:VLY4h80PBo6JwcScSXGKILsXEXgUs2ifVBgBhf4GfHh4A+IDkkCW/2m494bgj89k/d210x1L3zN3qJwSWMza5yqM66XXIA1t9YMO89fq3eNphNX9J7yA+g9ZMS8UvrbiZTtdMzi/XGyU1ziG+QIjQX2NqYCSyqWCfClw/L7x7UQ=,iv:8ufyBREc5Y+K4infXOORz1tDJrc3xVIQ5AKOTJn01vg=,tag:OdNVvUwt2y9ku4j6IVCVFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbCommonConfig
metadata:
    name: music
    namespace: default
spec:
    podSettings:
        nodeSelector:
            kubernetes.io/hostname: minis-7373
    network:
        publish: external
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRGo0bjZhMFgvNk4ydWV3
            elRxOWppL2JRTWRJVC94NG80Ti9XK01YMFh3CkZPeE1zTDVPUFV2UWZDUC9JWHRv
            M25hWkYzd1FDY00zUzRmUjVUL2s5MzAKLS0tIFViSlROZzRvazZLSWE4cHNsZ3Rl
            QjVQMFMwcHFVOUREeGFaemRHMjB6WFkKP1enPbuv2RGEHOmgKyGPl+lOf1bJtwr+
            iCjVcVIYRiMz1ROMQKgSQRmhx0zaufgn6hNsXTqjQ2G19AFfzGM+Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-27T16:13:35Z"
    mac: ENC[AES256_GCM,data:VLY4h80PBo6JwcScSXGKILsXEXgUs2ifVBgBhf4GfHh4A+IDkkCW/2m494bgj89k/d210x1L3zN3qJwSWMza5yqM66XXIA1t9YMO89fq3eNphNX9J7yA+g9ZMS8UvrbiZTtdMzi/XGyU1ziG+QIjQX2NqYCSyqWCfClw/L7x7UQ=,iv:8ufyBREc5Y+K4infXOORz1tDJrc3xVIQ5AKOTJn01vg=,tag:OdNVvUwt2y9ku4j6IVCVFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: music
    namespace: default
spec:
    securityConfig: musicusers
    commonConfig: music
    storage:
        pvc:
            name: roon-music
    readOnly: true
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRGo0bjZhMFgvNk4ydWV3
            elRxOWppL2JRTWRJVC94NG80Ti9XK01YMFh3CkZPeE1zTDVPUFV2UWZDUC9JWHRv
            M25hWkYzd1FDY00zUzRmUjVUL2s5MzAKLS0tIFViSlROZzRvazZLSWE4cHNsZ3Rl
            QjVQMFMwcHFVOUREeGFaemRHMjB6WFkKP1enPbuv2RGEHOmgKyGPl+lOf1bJtwr+
            iCjVcVIYRiMz1ROMQKgSQRmhx0zaufgn6hNsXTqjQ2G19AFfzGM+Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-27T16:13:35Z"
    mac: ENC[AES256_GCM,data:VLY4h80PBo6JwcScSXGKILsXEXgUs2ifVBgBhf4GfHh4A+IDkkCW/2m494bgj89k/d210x1L3zN3qJwSWMza5yqM66XXIA1t9YMO89fq3eNphNX9J7yA+g9ZMS8UvrbiZTtdMzi/XGyU1ziG+QIjQX2NqYCSyqWCfClw/L7x7UQ=,iv:8ufyBREc5Y+K4infXOORz1tDJrc3xVIQ5AKOTJn01vg=,tag:OdNVvUwt2y9ku4j6IVCVFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
