apiVersion: v1
kind: Secret
metadata:
    name: musicusers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:r0Zl869RWj7zUSjYaoRrwe2HdhGCutXVByxBhjggR+rtfXX0OKe8emvmtXQc2v/eZkvr+xc1UztfiCRPbhYfacdUUWhu7HcRBd7x7u8mv61vj+PqNpmNGrdrmDL66n1oumUe+xoh6mjYF/2wAt++7Cg73oJlOItqRYh2X7cR/etnLi5a9TDMZ8IM3Qgc+ZBppVzJz5GDHuPU7w==,iv:0WdSHySPOvtolG8gr2hdV2WbHcrWymbnyrCpxb2sicc=,tag:8TVdCOQJKW+jT71S9B7BuQ==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd25LdDFGUkV1M1NCNzE5
            bUMvVHR1VUtpRVV3NG5rQTZGYkRmYUNxc0dNCmQvelQ4VTdBN3U3UVl0WUZSa3o0
            SkQyNy9pT2xDRHdsWUhZVGVTbGZqVW8KLS0tIDJqclZ0OGQ4cXBNRlQwbis2S0FX
            ejZLTzlsOTdWRy9rcXdUZ2g4c1lvL2MKwzuHx85NX2hY5Z9mhnFwdWWO4w1FB4c/
            g6i9XFj+0Tw8YMeKs/V9je/BJRM6g7QK/SjAwz0XPKIqqAHdlsnXTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-27T17:11:48Z"
    mac: ENC[AES256_GCM,data:KFHMrvnDZx2ATvE7o3gPMbPnldiAJm60Eii83YX2Yu8j+OXtNiSnPG0NWxLejnQ/tQ6AGB/sK1VEO8C9Zs4W1kBYByxTcVOc7p8V29QBKRJoyA2jRLUlyIk88ELNVzh8gdQpO/muYaQsoCZ429q6Bz4hmMEhDpOJ2qs8T8tnBrY=,iv:aIIFfYJBdLfFki8zktSdoD0ZNtQi2Qyw+zcNYj+m52w=,tag:JkRlq48ZAWKWJ9xliXv3Hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
    name: musicusers
    namespace: default
spec:
    mode: user
    users:
        secret: musicusers
        key: demousers
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd25LdDFGUkV1M1NCNzE5
            bUMvVHR1VUtpRVV3NG5rQTZGYkRmYUNxc0dNCmQvelQ4VTdBN3U3UVl0WUZSa3o0
            SkQyNy9pT2xDRHdsWUhZVGVTbGZqVW8KLS0tIDJqclZ0OGQ4cXBNRlQwbis2S0FX
            ejZLTzlsOTdWRy9rcXdUZ2g4c1lvL2MKwzuHx85NX2hY5Z9mhnFwdWWO4w1FB4c/
            g6i9XFj+0Tw8YMeKs/V9je/BJRM6g7QK/SjAwz0XPKIqqAHdlsnXTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-27T17:11:48Z"
    mac: ENC[AES256_GCM,data:KFHMrvnDZx2ATvE7o3gPMbPnldiAJm60Eii83YX2Yu8j+OXtNiSnPG0NWxLejnQ/tQ6AGB/sK1VEO8C9Zs4W1kBYByxTcVOc7p8V29QBKRJoyA2jRLUlyIk88ELNVzh8gdQpO/muYaQsoCZ429q6Bz4hmMEhDpOJ2qs8T8tnBrY=,iv:aIIFfYJBdLfFki8zktSdoD0ZNtQi2Qyw+zcNYj+m52w=,tag:JkRlq48ZAWKWJ9xliXv3Hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbCommonConfig
metadata:
    name: music
    namespace: default
spec:
    podSettings:
        nodeSelector:
            kubernetes.io/hostname: minis-7373
    network:
        publish: external
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd25LdDFGUkV1M1NCNzE5
            bUMvVHR1VUtpRVV3NG5rQTZGYkRmYUNxc0dNCmQvelQ4VTdBN3U3UVl0WUZSa3o0
            SkQyNy9pT2xDRHdsWUhZVGVTbGZqVW8KLS0tIDJqclZ0OGQ4cXBNRlQwbis2S0FX
            ejZLTzlsOTdWRy9rcXdUZ2g4c1lvL2MKwzuHx85NX2hY5Z9mhnFwdWWO4w1FB4c/
            g6i9XFj+0Tw8YMeKs/V9je/BJRM6g7QK/SjAwz0XPKIqqAHdlsnXTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-27T17:11:48Z"
    mac: ENC[AES256_GCM,data:KFHMrvnDZx2ATvE7o3gPMbPnldiAJm60Eii83YX2Yu8j+OXtNiSnPG0NWxLejnQ/tQ6AGB/sK1VEO8C9Zs4W1kBYByxTcVOc7p8V29QBKRJoyA2jRLUlyIk88ELNVzh8gdQpO/muYaQsoCZ429q6Bz4hmMEhDpOJ2qs8T8tnBrY=,iv:aIIFfYJBdLfFki8zktSdoD0ZNtQi2Qyw+zcNYj+m52w=,tag:JkRlq48ZAWKWJ9xliXv3Hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: music
    namespace: default
spec:
    securityConfig: musicusers
    commonConfig: music
    storage:
        pvc:
            name: roon-music
    readOnly: false
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd25LdDFGUkV1M1NCNzE5
            bUMvVHR1VUtpRVV3NG5rQTZGYkRmYUNxc0dNCmQvelQ4VTdBN3U3UVl0WUZSa3o0
            SkQyNy9pT2xDRHdsWUhZVGVTbGZqVW8KLS0tIDJqclZ0OGQ4cXBNRlQwbis2S0FX
            ejZLTzlsOTdWRy9rcXdUZ2g4c1lvL2MKwzuHx85NX2hY5Z9mhnFwdWWO4w1FB4c/
            g6i9XFj+0Tw8YMeKs/V9je/BJRM6g7QK/SjAwz0XPKIqqAHdlsnXTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-27T17:11:48Z"
    mac: ENC[AES256_GCM,data:KFHMrvnDZx2ATvE7o3gPMbPnldiAJm60Eii83YX2Yu8j+OXtNiSnPG0NWxLejnQ/tQ6AGB/sK1VEO8C9Zs4W1kBYByxTcVOc7p8V29QBKRJoyA2jRLUlyIk88ELNVzh8gdQpO/muYaQsoCZ429q6Bz4hmMEhDpOJ2qs8T8tnBrY=,iv:aIIFfYJBdLfFki8zktSdoD0ZNtQi2Qyw+zcNYj+m52w=,tag:JkRlq48ZAWKWJ9xliXv3Hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
