apiVersion: v1
kind: Secret
metadata:
    name: musicusers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:pRZq63QLlEWfz03I2fd+r+KKGmJhtBFKOE6GodOU8obQhcGqqViw7mVo5A3J7ZG4vWlugwwpzpGLuSh7dPwk8rvYn0+01cLrEuUODEJtlVCRkVjBdokVRJLLUrc2fQVX9BkRE8WOfrqyUjF6xx0hniAHmN3wTvABVITEf55znTrUYMRz1WqI3QWlSLofhKLiGWP2jx4CuQHM6w==,iv:y0wJ//eA6R+IYSnrfdO1O7aj01JNrICu6bFaEhCcxC4=,tag:dom1ee5p/c9yp2QijytLYQ==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQitCS1F0WTc3WEw0RXQ5
            bFEzbHVkL2d2ZjNRalNnT1k2V2YwZUtMM2dzCk0rMGJ5TTN1RTh3bENrNm81MlJE
            K1VwaEpNcnBaMWxFd3BzSDRVZmltQncKLS0tIG9hNVFueHVpQlpFMXp2bCttaU85
            STNjSHlvRTU2TFNLaFUrRHEwVFJzMlEKp3dntELfWFVpPoDNej+vzYONEiyXBe9i
            Y0NXowBtvFGbjfl5nvsS9MHsEfJmO+sTpJI3FGiexdn/sWjmNQ2IKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T11:59:43Z"
    mac: ENC[AES256_GCM,data:7OJwK3XwyXJ5mE/sNDYspEl6In6n+OjIiei+L9MiDT2toEX0F1MSRHCQ9HrdeRS4YrbdVtDYXHhjLK3+rCyHO4A/tc9ZMJB5TOjzdbOmYdz1+tAVuNfBXWbaOUNdKKBmw26IWeRODeUssq4xP2AqXgB16j3piFaUhfWZIuzegTM=,iv:YRxFV3nnPYNdZXfGKGQXX3k9p9iTBeyuek0YXjK+e/8=,tag:tLJT62z5Mb2pjqzXvchKrQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
    name: musicusers
    namespace: default
spec:
    mode: user
    users:
        secret: musicusers
        key: demousers
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQitCS1F0WTc3WEw0RXQ5
            bFEzbHVkL2d2ZjNRalNnT1k2V2YwZUtMM2dzCk0rMGJ5TTN1RTh3bENrNm81MlJE
            K1VwaEpNcnBaMWxFd3BzSDRVZmltQncKLS0tIG9hNVFueHVpQlpFMXp2bCttaU85
            STNjSHlvRTU2TFNLaFUrRHEwVFJzMlEKp3dntELfWFVpPoDNej+vzYONEiyXBe9i
            Y0NXowBtvFGbjfl5nvsS9MHsEfJmO+sTpJI3FGiexdn/sWjmNQ2IKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T11:59:43Z"
    mac: ENC[AES256_GCM,data:7OJwK3XwyXJ5mE/sNDYspEl6In6n+OjIiei+L9MiDT2toEX0F1MSRHCQ9HrdeRS4YrbdVtDYXHhjLK3+rCyHO4A/tc9ZMJB5TOjzdbOmYdz1+tAVuNfBXWbaOUNdKKBmw26IWeRODeUssq4xP2AqXgB16j3piFaUhfWZIuzegTM=,iv:YRxFV3nnPYNdZXfGKGQXX3k9p9iTBeyuek0YXjK+e/8=,tag:tLJT62z5Mb2pjqzXvchKrQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbCommonConfig
metadata:
    name: music
    namespace: default
spec:
    podSettings:
        nodeSelector:
            kubernetes.io/hostname: minis-7373
    network:
        publish: external
    customGlobalConfig:
        configs:
            vfs_objects: fileid streams_xattr
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQitCS1F0WTc3WEw0RXQ5
            bFEzbHVkL2d2ZjNRalNnT1k2V2YwZUtMM2dzCk0rMGJ5TTN1RTh3bENrNm81MlJE
            K1VwaEpNcnBaMWxFd3BzSDRVZmltQncKLS0tIG9hNVFueHVpQlpFMXp2bCttaU85
            STNjSHlvRTU2TFNLaFUrRHEwVFJzMlEKp3dntELfWFVpPoDNej+vzYONEiyXBe9i
            Y0NXowBtvFGbjfl5nvsS9MHsEfJmO+sTpJI3FGiexdn/sWjmNQ2IKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T11:59:43Z"
    mac: ENC[AES256_GCM,data:7OJwK3XwyXJ5mE/sNDYspEl6In6n+OjIiei+L9MiDT2toEX0F1MSRHCQ9HrdeRS4YrbdVtDYXHhjLK3+rCyHO4A/tc9ZMJB5TOjzdbOmYdz1+tAVuNfBXWbaOUNdKKBmw26IWeRODeUssq4xP2AqXgB16j3piFaUhfWZIuzegTM=,iv:YRxFV3nnPYNdZXfGKGQXX3k9p9iTBeyuek0YXjK+e/8=,tag:tLJT62z5Mb2pjqzXvchKrQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: music
    namespace: default
spec:
    securityConfig: musicusers
    commonConfig: music
    storage:
        pvc:
            name: roon-music
    readOnly: false
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQitCS1F0WTc3WEw0RXQ5
            bFEzbHVkL2d2ZjNRalNnT1k2V2YwZUtMM2dzCk0rMGJ5TTN1RTh3bENrNm81MlJE
            K1VwaEpNcnBaMWxFd3BzSDRVZmltQncKLS0tIG9hNVFueHVpQlpFMXp2bCttaU85
            STNjSHlvRTU2TFNLaFUrRHEwVFJzMlEKp3dntELfWFVpPoDNej+vzYONEiyXBe9i
            Y0NXowBtvFGbjfl5nvsS9MHsEfJmO+sTpJI3FGiexdn/sWjmNQ2IKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T11:59:43Z"
    mac: ENC[AES256_GCM,data:7OJwK3XwyXJ5mE/sNDYspEl6In6n+OjIiei+L9MiDT2toEX0F1MSRHCQ9HrdeRS4YrbdVtDYXHhjLK3+rCyHO4A/tc9ZMJB5TOjzdbOmYdz1+tAVuNfBXWbaOUNdKKBmw26IWeRODeUssq4xP2AqXgB16j3piFaUhfWZIuzegTM=,iv:YRxFV3nnPYNdZXfGKGQXX3k9p9iTBeyuek0YXjK+e/8=,tag:tLJT62z5Mb2pjqzXvchKrQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
