apiVersion: v1
kind: Secret
metadata:
    name: musicusers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:VVBjuQn0ERhCA1DJ3KQZ3bfOKaBLGSA4tN8p5UhiaQimCFApDsewp3bbhHq2hkgVJ0hRXpOZV09smTCmEp5lDnazO/dLSYeHNcFPixKcAICx0Df43eMY3M+2tjgxY2OGk1YKKeEzzlEo9SeK9eBMrjEH6LEQ+kO/vs0p137x4uCAzjj4wT8bJUTMJh1jKiHs1XLKDvOC5Dw0Pg==,iv:GXn2Pv0FzFxjAdeLqevFIMR3AIAZnQ0YNPAgST6C/M8=,tag:yiJunsRWAUQ8XCAjuUPp9g==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcWlveE5RbGE3MSs0ZERr
            NGUzWEFOSkFLMmNaL2Nmc2ZxK1Z3QzFYN2prClF0RzdnVzRQRkhSdmJkRlVUUC9O
            Z0p4dnlKbGJ3YXVWQnNXcThscHpuV0EKLS0tIFpvQmY2VW8zcU9ndDIxRzBqQTdr
            aHE2cmRjd2xZTUczWkhKVk9QWEtnRXcKQtuvMXJ2vyvhpFvZUVxpkqdbXcHRkOKf
            Lc4oYC6l3tyZep8Eo8qiMHkyaNrqN1y+B+iJA83mGwCnFcm6z/wikQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T13:30:16Z"
    mac: ENC[AES256_GCM,data:+w2ufMSpLImr0iP1IYo13NzmRtPu4+xL1CaSxKtX8/tyQ5Fq8LwNbe7K07tbuHT2X6h4y/0harSaRsSDbD8OIRMduMtadBrB50MHAEFwTUFIUtuv+Qa3nwQsUQ8EYWL34CHIz7zeW0RlbtcjD8oEaDxF09smod8rKqYF/eMzj64=,iv:QTEZGGYiT2Vn4EFGxWaBWYeQBk2QDmRJ+mIsvC02+Qs=,tag:Il3OtFjua8031FCFeR5iRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
    name: musicusers
    namespace: default
spec:
    mode: user
    users:
        secret: musicusers
        key: demousers
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcWlveE5RbGE3MSs0ZERr
            NGUzWEFOSkFLMmNaL2Nmc2ZxK1Z3QzFYN2prClF0RzdnVzRQRkhSdmJkRlVUUC9O
            Z0p4dnlKbGJ3YXVWQnNXcThscHpuV0EKLS0tIFpvQmY2VW8zcU9ndDIxRzBqQTdr
            aHE2cmRjd2xZTUczWkhKVk9QWEtnRXcKQtuvMXJ2vyvhpFvZUVxpkqdbXcHRkOKf
            Lc4oYC6l3tyZep8Eo8qiMHkyaNrqN1y+B+iJA83mGwCnFcm6z/wikQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T13:30:16Z"
    mac: ENC[AES256_GCM,data:+w2ufMSpLImr0iP1IYo13NzmRtPu4+xL1CaSxKtX8/tyQ5Fq8LwNbe7K07tbuHT2X6h4y/0harSaRsSDbD8OIRMduMtadBrB50MHAEFwTUFIUtuv+Qa3nwQsUQ8EYWL34CHIz7zeW0RlbtcjD8oEaDxF09smod8rKqYF/eMzj64=,iv:QTEZGGYiT2Vn4EFGxWaBWYeQBk2QDmRJ+mIsvC02+Qs=,tag:Il3OtFjua8031FCFeR5iRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbCommonConfig
metadata:
    name: music
    namespace: default
spec:
    podSettings:
        nodeSelector:
            kubernetes.io/hostname: minis-7373
    network:
        publish: external
    customGlobalConfig:
        configs:
            strict rename: "Yes"
        useUnsafeCustomConfig: true
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcWlveE5RbGE3MSs0ZERr
            NGUzWEFOSkFLMmNaL2Nmc2ZxK1Z3QzFYN2prClF0RzdnVzRQRkhSdmJkRlVUUC9O
            Z0p4dnlKbGJ3YXVWQnNXcThscHpuV0EKLS0tIFpvQmY2VW8zcU9ndDIxRzBqQTdr
            aHE2cmRjd2xZTUczWkhKVk9QWEtnRXcKQtuvMXJ2vyvhpFvZUVxpkqdbXcHRkOKf
            Lc4oYC6l3tyZep8Eo8qiMHkyaNrqN1y+B+iJA83mGwCnFcm6z/wikQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T13:30:16Z"
    mac: ENC[AES256_GCM,data:+w2ufMSpLImr0iP1IYo13NzmRtPu4+xL1CaSxKtX8/tyQ5Fq8LwNbe7K07tbuHT2X6h4y/0harSaRsSDbD8OIRMduMtadBrB50MHAEFwTUFIUtuv+Qa3nwQsUQ8EYWL34CHIz7zeW0RlbtcjD8oEaDxF09smod8rKqYF/eMzj64=,iv:QTEZGGYiT2Vn4EFGxWaBWYeQBk2QDmRJ+mIsvC02+Qs=,tag:Il3OtFjua8031FCFeR5iRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: music
    namespace: default
spec:
    securityConfig: musicusers
    commonConfig: music
    storage:
        pvc:
            name: roon-music
    readOnly: false
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcWlveE5RbGE3MSs0ZERr
            NGUzWEFOSkFLMmNaL2Nmc2ZxK1Z3QzFYN2prClF0RzdnVzRQRkhSdmJkRlVUUC9O
            Z0p4dnlKbGJ3YXVWQnNXcThscHpuV0EKLS0tIFpvQmY2VW8zcU9ndDIxRzBqQTdr
            aHE2cmRjd2xZTUczWkhKVk9QWEtnRXcKQtuvMXJ2vyvhpFvZUVxpkqdbXcHRkOKf
            Lc4oYC6l3tyZep8Eo8qiMHkyaNrqN1y+B+iJA83mGwCnFcm6z/wikQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T13:30:16Z"
    mac: ENC[AES256_GCM,data:+w2ufMSpLImr0iP1IYo13NzmRtPu4+xL1CaSxKtX8/tyQ5Fq8LwNbe7K07tbuHT2X6h4y/0harSaRsSDbD8OIRMduMtadBrB50MHAEFwTUFIUtuv+Qa3nwQsUQ8EYWL34CHIz7zeW0RlbtcjD8oEaDxF09smod8rKqYF/eMzj64=,iv:QTEZGGYiT2Vn4EFGxWaBWYeQBk2QDmRJ+mIsvC02+Qs=,tag:Il3OtFjua8031FCFeR5iRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
