apiVersion: v1
kind: Secret
metadata:
    name: musicusers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:5g6FqajrRjtuaKOprrv9O+xAPfwadPilO36jR7/VfkZBm3yS3/fxoiW1XDtDJI94uvrQ6YvIhGufuQZ+pxYcKp8wsFnloV9EKkg2Y8NmhO26XmABdW5UE8lYXl1Hx05mnveWXJipo9XemXSzE7e/q4WBfiBhQPft9PU7U4j2UtMPw3Lwal6SdWhHY0T9M0x6FXEuxXi/XyusAQ==,iv:NJ7xELymgSLTZXllvo8bUaixQV7DyjmrfGy8STQcovE=,tag:H0Hypy5+B3ijVtWU8eJNwA==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aEZJbUV2akRoczVUZkp3
            TU1wU2QvV29YL2Zhc0g5c0w5QlN5OHdZYlNZClpjMEZQTEhTS2FBdWkrUkRaWWZu
            UHhVejRNM0k3ZjVNMGxnbjh1WERaV00KLS0tIFBSMEZhbE1kYlRDMmM2Sk1xbmZw
            MUFkcVpCankzOHJMeUswdHFMams0WEkK1V8BNGUiDRiIaW2XTpPLcYUs2MPGmgGI
            tLE8rt80LPaFoUqRj98lk1ZSfhxxq0PQy9+4FQKQBND9vsvQ+iTSrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T12:43:11Z"
    mac: ENC[AES256_GCM,data:w4AN4TI1h5hUmYV/Vh+xsM2i+y2BAKrKNXo7CzPY6S503PGb0AqSEDWUEpMONwWAVkzYs+2CSHM6YTzoI7gMY7P7TOvs83UzxDV3b/dk1m0/+AUhJRqAVNFNt7zBGD5QrDEk4plwHgU1EkM6N0gT+9v3lim+j6JAMcx6gyhpCRo=,iv:WTaF6Hlp/gqoYXS1PJCGuIfmuvgWIQcRj5fzQ6oIpLc=,tag:GGaRHySK0vS5C95CsNHvJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
    name: musicusers
    namespace: default
spec:
    mode: user
    users:
        secret: musicusers
        key: demousers
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aEZJbUV2akRoczVUZkp3
            TU1wU2QvV29YL2Zhc0g5c0w5QlN5OHdZYlNZClpjMEZQTEhTS2FBdWkrUkRaWWZu
            UHhVejRNM0k3ZjVNMGxnbjh1WERaV00KLS0tIFBSMEZhbE1kYlRDMmM2Sk1xbmZw
            MUFkcVpCankzOHJMeUswdHFMams0WEkK1V8BNGUiDRiIaW2XTpPLcYUs2MPGmgGI
            tLE8rt80LPaFoUqRj98lk1ZSfhxxq0PQy9+4FQKQBND9vsvQ+iTSrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T12:43:11Z"
    mac: ENC[AES256_GCM,data:w4AN4TI1h5hUmYV/Vh+xsM2i+y2BAKrKNXo7CzPY6S503PGb0AqSEDWUEpMONwWAVkzYs+2CSHM6YTzoI7gMY7P7TOvs83UzxDV3b/dk1m0/+AUhJRqAVNFNt7zBGD5QrDEk4plwHgU1EkM6N0gT+9v3lim+j6JAMcx6gyhpCRo=,iv:WTaF6Hlp/gqoYXS1PJCGuIfmuvgWIQcRj5fzQ6oIpLc=,tag:GGaRHySK0vS5C95CsNHvJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbCommonConfig
metadata:
    name: music
    namespace: default
spec:
    podSettings:
        nodeSelector:
            kubernetes.io/hostname: minis-7373
    network:
        publish: external
    customGlobalConfig:
        configs:
            strict rename: "Yes"
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aEZJbUV2akRoczVUZkp3
            TU1wU2QvV29YL2Zhc0g5c0w5QlN5OHdZYlNZClpjMEZQTEhTS2FBdWkrUkRaWWZu
            UHhVejRNM0k3ZjVNMGxnbjh1WERaV00KLS0tIFBSMEZhbE1kYlRDMmM2Sk1xbmZw
            MUFkcVpCankzOHJMeUswdHFMams0WEkK1V8BNGUiDRiIaW2XTpPLcYUs2MPGmgGI
            tLE8rt80LPaFoUqRj98lk1ZSfhxxq0PQy9+4FQKQBND9vsvQ+iTSrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T12:43:11Z"
    mac: ENC[AES256_GCM,data:w4AN4TI1h5hUmYV/Vh+xsM2i+y2BAKrKNXo7CzPY6S503PGb0AqSEDWUEpMONwWAVkzYs+2CSHM6YTzoI7gMY7P7TOvs83UzxDV3b/dk1m0/+AUhJRqAVNFNt7zBGD5QrDEk4plwHgU1EkM6N0gT+9v3lim+j6JAMcx6gyhpCRo=,iv:WTaF6Hlp/gqoYXS1PJCGuIfmuvgWIQcRj5fzQ6oIpLc=,tag:GGaRHySK0vS5C95CsNHvJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: music
    namespace: default
spec:
    securityConfig: musicusers
    commonConfig: music
    storage:
        pvc:
            name: roon-music
    readOnly: false
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aEZJbUV2akRoczVUZkp3
            TU1wU2QvV29YL2Zhc0g5c0w5QlN5OHdZYlNZClpjMEZQTEhTS2FBdWkrUkRaWWZu
            UHhVejRNM0k3ZjVNMGxnbjh1WERaV00KLS0tIFBSMEZhbE1kYlRDMmM2Sk1xbmZw
            MUFkcVpCankzOHJMeUswdHFMams0WEkK1V8BNGUiDRiIaW2XTpPLcYUs2MPGmgGI
            tLE8rt80LPaFoUqRj98lk1ZSfhxxq0PQy9+4FQKQBND9vsvQ+iTSrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T12:43:11Z"
    mac: ENC[AES256_GCM,data:w4AN4TI1h5hUmYV/Vh+xsM2i+y2BAKrKNXo7CzPY6S503PGb0AqSEDWUEpMONwWAVkzYs+2CSHM6YTzoI7gMY7P7TOvs83UzxDV3b/dk1m0/+AUhJRqAVNFNt7zBGD5QrDEk4plwHgU1EkM6N0gT+9v3lim+j6JAMcx6gyhpCRo=,iv:WTaF6Hlp/gqoYXS1PJCGuIfmuvgWIQcRj5fzQ6oIpLc=,tag:GGaRHySK0vS5C95CsNHvJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
