apiVersion: v1
kind: Secret
metadata:
    name: musicusers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:BKjjSpJjMcRjxiiRQ4Mbtm6aGPtcq+51X17gPOafo6O8nFYEnYMv3ZSeGCuJa8OUSk91yRBrR1/c3cdBE6xKUEnBz7HpWVyZMGA34KmYlfox8eMebSzPdrfvqCzoboILrKfLLFa/eSeSFJIYIEDGWPEBuot0QLOgizXAOf7YtY7MNk4Nt4m2Zt4hMWwtVzBtnN4YGToq2/eGcw==,iv:/1ucDmQlLKnv1vSgH9bwWjXw5YRozj2NtgVjtP8yO0M=,tag:7QMFnhAu8SC8HYbuVy3rnQ==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YnVSQ0hUSDI1WEo1M3BK
            aWVUdGY0L2FuMDhXY3ZiZ3psRG1wMWxHY1JJCnR3enAxbWI4WllWTU5XNytuZGZZ
            cXc4elF1bHVaWlcxeFN2YUtHMEM3VWsKLS0tIHFQWU9ZY0UxbkcrYkluTTNNcG9i
            cC9BMWVEWE1FUWpHa3J1eWYxcjJ5OFEKT0oy2qgMOubc7Xc3e0Q0+YsOmjBqRxXb
            Q5VjidgbNnHnuD0EUrPCHAymIHXn+pyrw109MXMaK3V9dRbTwsXw4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T06:36:08Z"
    mac: ENC[AES256_GCM,data:GZd67PVoRZYZ6qvN+CCsYIKMki2KmZpVHW5TTIuQJq3W3mni3jb6MpO4IgWFw2Ngh09/ZRjUNGiajXgiYLtVyvM77HDKoWD+qrh7BLTea92S3bFjUG8sYGfdavDsMAHCc7hggz7PE6MMDh6CShoomvtkcItX7zvIPjyF2T2L0w4=,iv:f9QKuR8JTrpzgFl/iFB6vakBGMxG1vO8H2nrGoxNb/s=,tag:ZC6Rb+kViLyX5dkGZRJreg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
    name: musicusers
    namespace: default
spec:
    mode: user
    users:
        secret: musicusers
        key: demousers
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YnVSQ0hUSDI1WEo1M3BK
            aWVUdGY0L2FuMDhXY3ZiZ3psRG1wMWxHY1JJCnR3enAxbWI4WllWTU5XNytuZGZZ
            cXc4elF1bHVaWlcxeFN2YUtHMEM3VWsKLS0tIHFQWU9ZY0UxbkcrYkluTTNNcG9i
            cC9BMWVEWE1FUWpHa3J1eWYxcjJ5OFEKT0oy2qgMOubc7Xc3e0Q0+YsOmjBqRxXb
            Q5VjidgbNnHnuD0EUrPCHAymIHXn+pyrw109MXMaK3V9dRbTwsXw4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T06:36:08Z"
    mac: ENC[AES256_GCM,data:GZd67PVoRZYZ6qvN+CCsYIKMki2KmZpVHW5TTIuQJq3W3mni3jb6MpO4IgWFw2Ngh09/ZRjUNGiajXgiYLtVyvM77HDKoWD+qrh7BLTea92S3bFjUG8sYGfdavDsMAHCc7hggz7PE6MMDh6CShoomvtkcItX7zvIPjyF2T2L0w4=,iv:f9QKuR8JTrpzgFl/iFB6vakBGMxG1vO8H2nrGoxNb/s=,tag:ZC6Rb+kViLyX5dkGZRJreg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbCommonConfig
metadata:
    name: music
    namespace: default
spec:
    podSettings:
        nodeSelector:
            kubernetes.io/hostname: minis-7373
    network:
        publish: external
        #    customGlobalConfig:
        #configs:
        #  additionalProperties: vfs_objects = streams_xattr
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YnVSQ0hUSDI1WEo1M3BK
            aWVUdGY0L2FuMDhXY3ZiZ3psRG1wMWxHY1JJCnR3enAxbWI4WllWTU5XNytuZGZZ
            cXc4elF1bHVaWlcxeFN2YUtHMEM3VWsKLS0tIHFQWU9ZY0UxbkcrYkluTTNNcG9i
            cC9BMWVEWE1FUWpHa3J1eWYxcjJ5OFEKT0oy2qgMOubc7Xc3e0Q0+YsOmjBqRxXb
            Q5VjidgbNnHnuD0EUrPCHAymIHXn+pyrw109MXMaK3V9dRbTwsXw4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T06:36:08Z"
    mac: ENC[AES256_GCM,data:GZd67PVoRZYZ6qvN+CCsYIKMki2KmZpVHW5TTIuQJq3W3mni3jb6MpO4IgWFw2Ngh09/ZRjUNGiajXgiYLtVyvM77HDKoWD+qrh7BLTea92S3bFjUG8sYGfdavDsMAHCc7hggz7PE6MMDh6CShoomvtkcItX7zvIPjyF2T2L0w4=,iv:f9QKuR8JTrpzgFl/iFB6vakBGMxG1vO8H2nrGoxNb/s=,tag:ZC6Rb+kViLyX5dkGZRJreg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: music
    namespace: default
spec:
    securityConfig: musicusers
    commonConfig: music
    storage:
        pvc:
            name: roon-music
    readOnly: false
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YnVSQ0hUSDI1WEo1M3BK
            aWVUdGY0L2FuMDhXY3ZiZ3psRG1wMWxHY1JJCnR3enAxbWI4WllWTU5XNytuZGZZ
            cXc4elF1bHVaWlcxeFN2YUtHMEM3VWsKLS0tIHFQWU9ZY0UxbkcrYkluTTNNcG9i
            cC9BMWVEWE1FUWpHa3J1eWYxcjJ5OFEKT0oy2qgMOubc7Xc3e0Q0+YsOmjBqRxXb
            Q5VjidgbNnHnuD0EUrPCHAymIHXn+pyrw109MXMaK3V9dRbTwsXw4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T06:36:08Z"
    mac: ENC[AES256_GCM,data:GZd67PVoRZYZ6qvN+CCsYIKMki2KmZpVHW5TTIuQJq3W3mni3jb6MpO4IgWFw2Ngh09/ZRjUNGiajXgiYLtVyvM77HDKoWD+qrh7BLTea92S3bFjUG8sYGfdavDsMAHCc7hggz7PE6MMDh6CShoomvtkcItX7zvIPjyF2T2L0w4=,iv:f9QKuR8JTrpzgFl/iFB6vakBGMxG1vO8H2nrGoxNb/s=,tag:ZC6Rb+kViLyX5dkGZRJreg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
