apiVersion: v1
kind: Secret
metadata:
    name: musicusers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:p8OB0kC7U/7lCI+nv7PQbmR2iBO4D6DIaS9xGBxcXpqzNnocZeUyd2Abqz2rFprjAIM22fo/q1NgfeFVGaUKaPopQbqj8kBE4a8Ls6qCU+1EuBUNPGBkXugxP58Rh5dfYrO0wi5AWw3IFxLNxW6KB7JlFhW4cUALz0/YoF4HII+eJ5jNUd7+ZFuRK2LTdBUovi5D4qJi+cwKfQ==,iv:JcMlF1Ow6n128I+bX3x9GFXUc3T5wIfvY5uN1cSnaao=,tag:UEG/VZlupXSWPptJ6M2KCg==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOVlNVmloSDBrQ2ZkbG9X
            S28wM3RjWTBrektGSnhNWW9zOWlXdWFXdGhzClVDcnpvZHg4ZDNLT2orM09jV1Vk
            dGRwZFdsUy9LaVhEUmo4Y1JGMmZvK0EKLS0tIDYrQVh0dXUwaWpCT2xORndMVmxX
            RXJRYjZ2eFBONGZ2bjFOb0s3bkNDL28Ke0pDqa20Dh7b0Z4nntrdEyzjIyTyqkc/
            9YgS+4rocKiBLMG2tZQb31Q7T+Da5JmK4adJDkch7oLHZG2vl0KGpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T13:36:45Z"
    mac: ENC[AES256_GCM,data:2DSkaeG5bwzGaP5+LHeR3+k4LpggZ0HP1gjl3+75EuPPpUtAzaOjik84Sc5OwyaLJGx1/SU7R7enydr7BR9UDelWYVd8ZObb9v6nZNbCskaJdZMyDRVKVAJ1zEBKANcrCDn2OVhd0ra/+9DGof4FIp2QJ4zS1wRAPqtlI5u3hqQ=,iv:AGOT19l9F/lieQahdP1tFB2+XvuO3c8TUgu9PKbRGvs=,tag:CVVlRMcB/0s2RajufQSo/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
    name: musicusers
    namespace: default
spec:
    mode: user
    users:
        secret: musicusers
        key: demousers
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOVlNVmloSDBrQ2ZkbG9X
            S28wM3RjWTBrektGSnhNWW9zOWlXdWFXdGhzClVDcnpvZHg4ZDNLT2orM09jV1Vk
            dGRwZFdsUy9LaVhEUmo4Y1JGMmZvK0EKLS0tIDYrQVh0dXUwaWpCT2xORndMVmxX
            RXJRYjZ2eFBONGZ2bjFOb0s3bkNDL28Ke0pDqa20Dh7b0Z4nntrdEyzjIyTyqkc/
            9YgS+4rocKiBLMG2tZQb31Q7T+Da5JmK4adJDkch7oLHZG2vl0KGpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T13:36:45Z"
    mac: ENC[AES256_GCM,data:2DSkaeG5bwzGaP5+LHeR3+k4LpggZ0HP1gjl3+75EuPPpUtAzaOjik84Sc5OwyaLJGx1/SU7R7enydr7BR9UDelWYVd8ZObb9v6nZNbCskaJdZMyDRVKVAJ1zEBKANcrCDn2OVhd0ra/+9DGof4FIp2QJ4zS1wRAPqtlI5u3hqQ=,iv:AGOT19l9F/lieQahdP1tFB2+XvuO3c8TUgu9PKbRGvs=,tag:CVVlRMcB/0s2RajufQSo/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbCommonConfig
metadata:
    name: music
    namespace: default
spec:
    podSettings:
        nodeSelector:
            kubernetes.io/hostname: minis-7373
    network:
        publish: external
    customGlobalConfig:
        configs:
            additionalProperties: vfs_objects = streams_xattr
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOVlNVmloSDBrQ2ZkbG9X
            S28wM3RjWTBrektGSnhNWW9zOWlXdWFXdGhzClVDcnpvZHg4ZDNLT2orM09jV1Vk
            dGRwZFdsUy9LaVhEUmo4Y1JGMmZvK0EKLS0tIDYrQVh0dXUwaWpCT2xORndMVmxX
            RXJRYjZ2eFBONGZ2bjFOb0s3bkNDL28Ke0pDqa20Dh7b0Z4nntrdEyzjIyTyqkc/
            9YgS+4rocKiBLMG2tZQb31Q7T+Da5JmK4adJDkch7oLHZG2vl0KGpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T13:36:45Z"
    mac: ENC[AES256_GCM,data:2DSkaeG5bwzGaP5+LHeR3+k4LpggZ0HP1gjl3+75EuPPpUtAzaOjik84Sc5OwyaLJGx1/SU7R7enydr7BR9UDelWYVd8ZObb9v6nZNbCskaJdZMyDRVKVAJ1zEBKANcrCDn2OVhd0ra/+9DGof4FIp2QJ4zS1wRAPqtlI5u3hqQ=,iv:AGOT19l9F/lieQahdP1tFB2+XvuO3c8TUgu9PKbRGvs=,tag:CVVlRMcB/0s2RajufQSo/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: music
    namespace: default
spec:
    securityConfig: musicusers
    commonConfig: music
    storage:
        pvc:
            name: roon-music
    readOnly: false
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOVlNVmloSDBrQ2ZkbG9X
            S28wM3RjWTBrektGSnhNWW9zOWlXdWFXdGhzClVDcnpvZHg4ZDNLT2orM09jV1Vk
            dGRwZFdsUy9LaVhEUmo4Y1JGMmZvK0EKLS0tIDYrQVh0dXUwaWpCT2xORndMVmxX
            RXJRYjZ2eFBONGZ2bjFOb0s3bkNDL28Ke0pDqa20Dh7b0Z4nntrdEyzjIyTyqkc/
            9YgS+4rocKiBLMG2tZQb31Q7T+Da5JmK4adJDkch7oLHZG2vl0KGpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T13:36:45Z"
    mac: ENC[AES256_GCM,data:2DSkaeG5bwzGaP5+LHeR3+k4LpggZ0HP1gjl3+75EuPPpUtAzaOjik84Sc5OwyaLJGx1/SU7R7enydr7BR9UDelWYVd8ZObb9v6nZNbCskaJdZMyDRVKVAJ1zEBKANcrCDn2OVhd0ra/+9DGof4FIp2QJ4zS1wRAPqtlI5u3hqQ=,iv:AGOT19l9F/lieQahdP1tFB2+XvuO3c8TUgu9PKbRGvs=,tag:CVVlRMcB/0s2RajufQSo/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
