apiVersion: v1
kind: Secret
metadata:
    name: musicusers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:kFUs+EhvolRWQqiEbqaOgf2NG++C8vWI5ecBjJ7kWq+UlVweayiBEgXEFCehxLoB3G3+gnUF7HAYvBADAyHZDj/qF2El2DkFjUkL2kOt5hiovUm+9FsNaiOu+HRuK5wuO4RPrHnv7CJ69S9fSO6mznLIjgh8DRQkUZHDoYfJ/s2XsUtDNmwC8M2LcG1ZKFgv5s3XQ2qb1pcOVw==,iv:vIVJM6R3XKUgC4d0vzvl725jR7Cji78U2/O38dBAow0=,tag:NHrRmzozgokB2Qe1OlQPew==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dTl6clBkcTJnS1JZQ2FQ
            Qk1DaFJlSkdHaVhqVTFMTzMzYmhvaHBlU0dzCmhOQTR4WXlVV2lWeVNMRllXRysr
            ZGVuRlREZmN4OFhUaWp0UGxhSUdoaFUKLS0tIHdKeGIxTThJYkZaM3ZjcUZxSDVs
            cmtNc2JPRWNqR25WTlV1TzJMeStWZDAK8z/oVAY8B3A1bHfb80KqLYwYD0gcQlA4
            VqyC/nLmTVwkzDOImyy4psaCMzQQAybBiVTSII/Norw14Ui8BqAOJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T11:47:41Z"
    mac: ENC[AES256_GCM,data:UytzIc5VNN/cVC0UFQ/LXxF0hhzrVz9sSxaPkSQAGP3ichxEF8gRBDYoev0/f/V+IyG6uMa2g18HmULPGHLtakbhaTx+wl5/PwkLJdL148rIR0zPIy5pZYgu4OvNhXF+oBVLoGlR2ZS2hCqI5B7CEvj4jns0pt2SlKmWx/MKXdA=,iv:qemw9ifg0DQx8xv/Q6647vrcQ36OA0xApxQyjyAZRis=,tag:XNOUmccSWvYKVE2ZrnevMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
    name: musicusers
    namespace: default
spec:
    mode: user
    users:
        secret: musicusers
        key: demousers
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dTl6clBkcTJnS1JZQ2FQ
            Qk1DaFJlSkdHaVhqVTFMTzMzYmhvaHBlU0dzCmhOQTR4WXlVV2lWeVNMRllXRysr
            ZGVuRlREZmN4OFhUaWp0UGxhSUdoaFUKLS0tIHdKeGIxTThJYkZaM3ZjcUZxSDVs
            cmtNc2JPRWNqR25WTlV1TzJMeStWZDAK8z/oVAY8B3A1bHfb80KqLYwYD0gcQlA4
            VqyC/nLmTVwkzDOImyy4psaCMzQQAybBiVTSII/Norw14Ui8BqAOJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T11:47:41Z"
    mac: ENC[AES256_GCM,data:UytzIc5VNN/cVC0UFQ/LXxF0hhzrVz9sSxaPkSQAGP3ichxEF8gRBDYoev0/f/V+IyG6uMa2g18HmULPGHLtakbhaTx+wl5/PwkLJdL148rIR0zPIy5pZYgu4OvNhXF+oBVLoGlR2ZS2hCqI5B7CEvj4jns0pt2SlKmWx/MKXdA=,iv:qemw9ifg0DQx8xv/Q6647vrcQ36OA0xApxQyjyAZRis=,tag:XNOUmccSWvYKVE2ZrnevMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbCommonConfig
metadata:
    name: music
    namespace: default
spec:
    podSettings:
        nodeSelector:
            kubernetes.io/hostname: minis-7373
    network:
        publish: external
    useUnsafeCustomConfig: true
    customGlobalConfig:
        configs:
            vfs_objects: fileid streams_xattr
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dTl6clBkcTJnS1JZQ2FQ
            Qk1DaFJlSkdHaVhqVTFMTzMzYmhvaHBlU0dzCmhOQTR4WXlVV2lWeVNMRllXRysr
            ZGVuRlREZmN4OFhUaWp0UGxhSUdoaFUKLS0tIHdKeGIxTThJYkZaM3ZjcUZxSDVs
            cmtNc2JPRWNqR25WTlV1TzJMeStWZDAK8z/oVAY8B3A1bHfb80KqLYwYD0gcQlA4
            VqyC/nLmTVwkzDOImyy4psaCMzQQAybBiVTSII/Norw14Ui8BqAOJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T11:47:41Z"
    mac: ENC[AES256_GCM,data:UytzIc5VNN/cVC0UFQ/LXxF0hhzrVz9sSxaPkSQAGP3ichxEF8gRBDYoev0/f/V+IyG6uMa2g18HmULPGHLtakbhaTx+wl5/PwkLJdL148rIR0zPIy5pZYgu4OvNhXF+oBVLoGlR2ZS2hCqI5B7CEvj4jns0pt2SlKmWx/MKXdA=,iv:qemw9ifg0DQx8xv/Q6647vrcQ36OA0xApxQyjyAZRis=,tag:XNOUmccSWvYKVE2ZrnevMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: music
    namespace: default
spec:
    securityConfig: musicusers
    commonConfig: music
    storage:
        pvc:
            name: roon-music
    readOnly: false
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dTl6clBkcTJnS1JZQ2FQ
            Qk1DaFJlSkdHaVhqVTFMTzMzYmhvaHBlU0dzCmhOQTR4WXlVV2lWeVNMRllXRysr
            ZGVuRlREZmN4OFhUaWp0UGxhSUdoaFUKLS0tIHdKeGIxTThJYkZaM3ZjcUZxSDVs
            cmtNc2JPRWNqR25WTlV1TzJMeStWZDAK8z/oVAY8B3A1bHfb80KqLYwYD0gcQlA4
            VqyC/nLmTVwkzDOImyy4psaCMzQQAybBiVTSII/Norw14Ui8BqAOJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T11:47:41Z"
    mac: ENC[AES256_GCM,data:UytzIc5VNN/cVC0UFQ/LXxF0hhzrVz9sSxaPkSQAGP3ichxEF8gRBDYoev0/f/V+IyG6uMa2g18HmULPGHLtakbhaTx+wl5/PwkLJdL148rIR0zPIy5pZYgu4OvNhXF+oBVLoGlR2ZS2hCqI5B7CEvj4jns0pt2SlKmWx/MKXdA=,iv:qemw9ifg0DQx8xv/Q6647vrcQ36OA0xApxQyjyAZRis=,tag:XNOUmccSWvYKVE2ZrnevMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
