---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 30m
  chart:
    spec:
      chart: kyverno
      version: 3.5.0
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
      interval: 30m
  values:
    config:
      resourceFiltersExclude:
        - '[Node,*,*]'
        - '[Node/*,*,*]'
    backgroundController:
      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - ""
              resources:
                - nodes
              verbs:
                - create
                - update
                - patch
                - delete
                - get
                - list
