apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metallb
  namespace: default
spec:
  interval: 5m
  url: https://github.com/metallb/metallb
  ref:
    tag: 0.14.3
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: metallb
  path: "./config/native"
  prune: true
  timeout: 1m
