---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    tag: 0.14.3
  url: https://github.com/metallb/metallb
