---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-release
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-repo
  interval: 1m0s
  values:
    grafana:
      service:
        type: LoadBalancer
        annotations:
          - external-dns.alpha.kubernetes.io/hostname: longhorn.k8s.musikcheck.dk.
