---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-release
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: prometheus-repo
  interval: 15m0s
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-values
