apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  - pushover-creds.yaml
  - alertmanager-pushover.yaml
  - longhorn-monitor.yaml

configMapGenerator:
- name: prometheus-values
  namespace: monitoring
  files:
  - values.yaml=my-values.yaml
configurations:
  - kustomizeconfig.yaml
