grafana:
  service:
    type: LoadBalancer
    annotations: {
      external-dns.alpha.kubernetes.io/hostname: grafana.k8s.musikcheck.dk.
    }
  dashboardProviders:
    dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'default'
       orgId: 1
       folder: 'default'
       type: file
       disableDeletion: true
       editable: true
       options:
         path: /var/lib/grafana/dashboards/standard
  dashboards:
    default:  
      longhorn:
        gnetId: 16888
        revision: 9
        datasource: prometheus
prometheus:
  service:
    type: LoadBalancer
    annotations: {
      external-dns.alpha.kubernetes.io/hostname: prometheus.k8s.musikcheck.dk.
    }
alertmanager:
  service:
    type: LoadBalancer
    annotations: {
      external-dns.alpha.kubernetes.io/hostname: alertmanager.k8s.musikcheck.dk.
    }
