grafana:
  service:
    type: LoadBalancer
    annotations: {
      external-dns.alpha.kubernetes.io/hostname: grafana.k8s.musikcheck.dk.
    }
  dashboards:
    default:  
      longhorn:
        gnetId: 16888
prometheus:
  service:
    type: LoadBalancer
    annotations: {
      external-dns.alpha.kubernetes.io/hostname: prometheus.k8s.musikcheck.dk.
    }
