apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-longhorn-annotation
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
  - name: add-longhorn-disks
    match:
      all:
      - resources:
          kinds: 
          - Node
    mutate:
      targets:
        - apiVersion: v1
          kind: Node
      patchStrategicMerge:
        metadata:
          annotations:
            +(gylle): 'gylle'
            #node.longhorn.io/default-disks-config: '[ { "path":"/var/lib/longhorn", "allowScheduling":true }, { "name":"flash", "path":"/mnt/data", "allowScheduling":true, "tags":[ "ssd", "fast" ] }]' 
