apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-longhorn-annotation
spec:
  generateExistingOnPolicyUpdate: true
  rules:
  - name: add-longhorn-disks
    match:
      any:
      - resources:
        kinds:
        - Pod
        namespace: default
    mutate:
      targets:
        - apiVersion: v1
          kind: Pod
          name: "{{ request.object.metadata.name }}"
      patchStrategicMerge:
        metadata:
          labels:
            gylle: gylle
              #node.longhorn.io/default-disks-config: '[ { "path":"/var/lib/longhorn", "allowScheduling":true }, { "name":"flash", "path":"/mnt/data", "allowScheduling":true, "tags":[ "ssd", "fast" ] }]' 
