apiVersion: v1
kind: Secret
metadata:
    name: videousers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:ZVtGxxOwakc2m4/6mQQMTdJ2FMUVe7hOZ2z0VERAJzdi35O0028lKjJTaqHxDXwbK2zqiBIv5XJDJbB8BGW8SGKJjzmitDBCcTETdbhp151SDfxDcIUlPJ7yae91D75sTshuxiDa3eROXMQbFvs54KoUbzyPMRArwWkFSaX/rXtECsHfn+yiwlBjABVY5J0HQAT/iLVd/Jh8Vg==,iv:jd2fGUdoSgS3NAa6FBf5OST17FqwTNo/7KTc2yut65s=,tag:nP3UNIWI2PYHdw6H7wcwvw==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRnYvcXhtVjk0Q0diZXhx
            cVZjb0sxbnRTaE4wS09CeHhHSVlDNGhIMHc0Cnk0b2h2YmdWcUNnVis5bkRGeW4x
            SlduN3RFU2VIektzR3NZbkVLQTZsOEEKLS0tIFdGQlR0TUJVWkw2N1NpWEd4dlZj
            dWxHcDh1eHNVaHp1K3d6Snhkc0FvbWsKB+WTe3KkvYgDtSTafRTO082MONPEougF
            IpR/9Gya2DwzBKnDMoyo899vbJJXVrU+hvDI6wxbCDxFF86XEHye5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T08:08:28Z"
    mac: ENC[AES256_GCM,data:h5la9UNIN+xdlfVdrDc2jOzHdm2KeybN5+gcURakh0pCE2eTBJEaln5bkJVRz0HLXso+4KTLJ3zuMKuBApMkb3LRgNB6fNYvl+7CX11UACuPcfKyVrjtU/+W8gmy2gQFbVgtJbkfSHMctVvUbbjwMyq42SGYB+JYAQCSEfreqAM=,iv:h7GjynZMDcdq6oigBhgLKSCFI3jJ04Si6A8lbKG5zBk=,tag:5M1RBc0sM2sawImYI83PaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
    name: videousers
    namespace: default
spec:
    mode: user
    users:
        secret: videousers
        key: demousers
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRnYvcXhtVjk0Q0diZXhx
            cVZjb0sxbnRTaE4wS09CeHhHSVlDNGhIMHc0Cnk0b2h2YmdWcUNnVis5bkRGeW4x
            SlduN3RFU2VIektzR3NZbkVLQTZsOEEKLS0tIFdGQlR0TUJVWkw2N1NpWEd4dlZj
            dWxHcDh1eHNVaHp1K3d6Snhkc0FvbWsKB+WTe3KkvYgDtSTafRTO082MONPEougF
            IpR/9Gya2DwzBKnDMoyo899vbJJXVrU+hvDI6wxbCDxFF86XEHye5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T08:08:28Z"
    mac: ENC[AES256_GCM,data:h5la9UNIN+xdlfVdrDc2jOzHdm2KeybN5+gcURakh0pCE2eTBJEaln5bkJVRz0HLXso+4KTLJ3zuMKuBApMkb3LRgNB6fNYvl+7CX11UACuPcfKyVrjtU/+W8gmy2gQFbVgtJbkfSHMctVvUbbjwMyq42SGYB+JYAQCSEfreqAM=,iv:h7GjynZMDcdq6oigBhgLKSCFI3jJ04Si6A8lbKG5zBk=,tag:5M1RBc0sM2sawImYI83PaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: video
    namespace: default
spec:
    securityConfig: videousers
    commonConfig: music
    readOnly: false
    storage:
        pvc:
            spec:
                accessModes:
                    - ReadWriteOnce
                resources:
                    requests:
                        storage: 1100Gi
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRnYvcXhtVjk0Q0diZXhx
            cVZjb0sxbnRTaE4wS09CeHhHSVlDNGhIMHc0Cnk0b2h2YmdWcUNnVis5bkRGeW4x
            SlduN3RFU2VIektzR3NZbkVLQTZsOEEKLS0tIFdGQlR0TUJVWkw2N1NpWEd4dlZj
            dWxHcDh1eHNVaHp1K3d6Snhkc0FvbWsKB+WTe3KkvYgDtSTafRTO082MONPEougF
            IpR/9Gya2DwzBKnDMoyo899vbJJXVrU+hvDI6wxbCDxFF86XEHye5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T08:08:28Z"
    mac: ENC[AES256_GCM,data:h5la9UNIN+xdlfVdrDc2jOzHdm2KeybN5+gcURakh0pCE2eTBJEaln5bkJVRz0HLXso+4KTLJ3zuMKuBApMkb3LRgNB6fNYvl+7CX11UACuPcfKyVrjtU/+W8gmy2gQFbVgtJbkfSHMctVvUbbjwMyq42SGYB+JYAQCSEfreqAM=,iv:h7GjynZMDcdq6oigBhgLKSCFI3jJ04Si6A8lbKG5zBk=,tag:5M1RBc0sM2sawImYI83PaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
