apiVersion: v1
kind: Secret
metadata:
    name: videousers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:NNZkxmjy2/vL84JmjmuIoGhMhMeyK0sYWxdR6JiWzhNB9GZnH7lOmdz5rTWiRD7i4Bsk2WWM5MFompC2qaA2X2ybkQSjJNGKnWDItdnMb5G/K7lVhJZNMXVApXxDWKV3Z6Np6VBqT4Xh91wVx0gor9+0Gi88iWeLYVdZ2J1BagyRpMB+nwx5g7E+jbLPXggW2KWdra/7wST2Nw==,iv:TFWgF52XIs5T5wxSsv0A2T49e+QfuRXIadHu5/eN/aM=,tag:9QkB4hHcxhtwMpTiSchjFQ==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZnJMWFJvM0V3YlFzcGhH
            clNvRUlRL1hBRTE4TEVNMllqdm0yeE9JRkJVCjkxeUVTalNBZXdlYmFCaFMzZjRO
            TDdwUmQ1ZnFkTjdoSWNud2FLajR4c3MKLS0tIHdDeXdCZEpXbHNtWmd2UWIwNlkz
            ZXNscE9DN0hKWlJ2dVhXSDZGU2Q4L1UKXQu6qmOQ6cqRjq662fAvK4xSFEZJXpdb
            VgrDlxf2LQO5obV655+4RJBC/MzvruBHNFZfkInjVRC5F8iBWqUSHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T10:12:17Z"
    mac: ENC[AES256_GCM,data:wm7ikR5vi1+3XXX1UfO1xLJyoU2Y2XTWlguJhlsSImxu/EJwgvMpa1yLtDVYZSy1PYlZWpcGyRQASFUTsFqcR4uv28w76sj9/54nWwDj+/1klvHBoZyecO5lPiKJbU3jSr2K/DLbbpwcAoCO8SA61VEcCduIBS/9Up9RA0vazhQ=,iv:92PM22+Mo16JH/BDvIfwIXDPb+MdNB3yX1pCmDl6+2s=,tag:TvxDm3krP77dE0KFl60j2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
    name: videousers
    namespace: default
spec:
    mode: user
    users:
        secret: videousers
        key: demousers
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZnJMWFJvM0V3YlFzcGhH
            clNvRUlRL1hBRTE4TEVNMllqdm0yeE9JRkJVCjkxeUVTalNBZXdlYmFCaFMzZjRO
            TDdwUmQ1ZnFkTjdoSWNud2FLajR4c3MKLS0tIHdDeXdCZEpXbHNtWmd2UWIwNlkz
            ZXNscE9DN0hKWlJ2dVhXSDZGU2Q4L1UKXQu6qmOQ6cqRjq662fAvK4xSFEZJXpdb
            VgrDlxf2LQO5obV655+4RJBC/MzvruBHNFZfkInjVRC5F8iBWqUSHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T10:12:17Z"
    mac: ENC[AES256_GCM,data:wm7ikR5vi1+3XXX1UfO1xLJyoU2Y2XTWlguJhlsSImxu/EJwgvMpa1yLtDVYZSy1PYlZWpcGyRQASFUTsFqcR4uv28w76sj9/54nWwDj+/1klvHBoZyecO5lPiKJbU3jSr2K/DLbbpwcAoCO8SA61VEcCduIBS/9Up9RA0vazhQ=,iv:92PM22+Mo16JH/BDvIfwIXDPb+MdNB3yX1pCmDl6+2s=,tag:TvxDm3krP77dE0KFl60j2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: video
    namespace: default
spec:
    securityConfig: videouser
    commonConfig: music
    readOnly: false
    storage:
        pvc:
            spec:
                accessModes:
                    - ReadWriteOnce
                resources:
                    requests:
                        storage: 1100Gi
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZnJMWFJvM0V3YlFzcGhH
            clNvRUlRL1hBRTE4TEVNMllqdm0yeE9JRkJVCjkxeUVTalNBZXdlYmFCaFMzZjRO
            TDdwUmQ1ZnFkTjdoSWNud2FLajR4c3MKLS0tIHdDeXdCZEpXbHNtWmd2UWIwNlkz
            ZXNscE9DN0hKWlJ2dVhXSDZGU2Q4L1UKXQu6qmOQ6cqRjq662fAvK4xSFEZJXpdb
            VgrDlxf2LQO5obV655+4RJBC/MzvruBHNFZfkInjVRC5F8iBWqUSHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T10:12:17Z"
    mac: ENC[AES256_GCM,data:wm7ikR5vi1+3XXX1UfO1xLJyoU2Y2XTWlguJhlsSImxu/EJwgvMpa1yLtDVYZSy1PYlZWpcGyRQASFUTsFqcR4uv28w76sj9/54nWwDj+/1klvHBoZyecO5lPiKJbU3jSr2K/DLbbpwcAoCO8SA61VEcCduIBS/9Up9RA0vazhQ=,iv:92PM22+Mo16JH/BDvIfwIXDPb+MdNB3yX1pCmDl6+2s=,tag:TvxDm3krP77dE0KFl60j2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
