apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: video2
    namespace: default
spec:
    securityConfig: videousers
    commonConfig: music
    readOnly: false
    storage:
        pvc:
            spec:
                accessModes:
                    - ReadWriteOnce
                resources:
                    requests:
                        storage: 1100Gi
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOFlFRzhOMFkvM0t6RndO
            OWplZ3hnUkRxMDlJTGdYUzJDREovdHNnWnd3CkJDbWxsM0lJU3ZtbW9rV1ZkSVpv
            a0ZmQ05pQ05Ga2d3dTRodFM5SXo1TlEKLS0tIFVBRWFwTHpnR1JpSzJ4aEFKRXFW
            QWVjMWlnZlJqclFBTVd0N0kyYStYS2cKdr9lA5Ek56Kr0RsDEzg1p+sgO8cpr+oM
            eDVuSNoCvz4CHdCwigjc29NZbETFSU4comQ/uZtxAzBN7b413buozg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T06:17:12Z"
    mac: ENC[AES256_GCM,data:DCdvua+qYQfe/WlOAxBeZx8IGY1GAP9heYVblf1V8aFaog97jEcVlu9lh1JkKoR5+bGwXj/xZomd3J22YHwiNEDgUzSqdKHCzGXA7Rs7Odj0AWZzawLGA8MHrNLqrqy/8uRNpLj/J7V3kA0P9DGW+npBen5WDAdf29XN8Q73wgk=,iv:4exPPP2ZQNIANcw8x1ia/eYye27bTFRRCsTQYrfUrXI=,tag:pjlwmyDqfmKQZC7m33riAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
