apiVersion: v1
kind: Secret
metadata:
    name: videousers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:0wS41tHoS9Qi4ub2rpH+wJn/FCONf899cHvfH8Yqx6IwICIBk/KPI1/8VssPev66bYPjyq3nXSRGHKJ6s1KOUeZzD+m9Ij5ZM9ZSyzVEsWJ1GImm98XiDTrYHlJyJbJzctSu5XjVOT6opFWnqc3+QP1nhtmbBFz1YKD/isTWd96M6wGKujR8MolcefG/MPFdNsa220rHIZVbDw==,iv:ZbGGDabFU6GUsXk+dMd/2bbCIr28HhubAHvijBNtpaA=,tag:Xo33Z6bCIxZtG/bLDNvX3A==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNmYvb09EZVNKQmE2T1o3
            Q2RyUkN2V3dRa09PdGl4RkROVHkzSC9SenlvCkJnd3lUdGJCNVRnWWphWmNkUHZj
            VWVJZjNlM1pVaFpmYzVFblhLU2pORjQKLS0tIG1vK1ZjUldka2EwUDhjRGhwaGxT
            ZE1KWHJpZER6Rlc1WEQ0NDUrbFFZOHcKbOQlcZtWIORzYoIAEFuZUPYS+Ta83H4z
            Z3y/OzieEgn6XnavA2VMZV4ouZxY+p1S0STKA7s7z3J8ixHz1sPyeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T17:54:44Z"
    mac: ENC[AES256_GCM,data:9Kj68TKXJon6e1b0th1ubESMP+KxmSNnWFPDT2eE7Bz273f5qSWF6+sb+1G1pWzRVpZ5BTs/sP6LlSHPVnPedzIPsVzV6IET4MjieQir1n4+4vFuTKZpTTGIUAsatDvEom5nEj0XHckXl49itUZNUx5YXuRWM2mICWarUZitPrE=,iv:3yJAUVF2bN0Ysz8hV5DiXUJ7cGfy2h5VeecWvToqltM=,tag:DTgDtRtjoMEyexcwd/xYzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
    name: videoconfig
    namespace: default
spec:
    mode: user
    users:
        secret: videousers
        key: demousers
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNmYvb09EZVNKQmE2T1o3
            Q2RyUkN2V3dRa09PdGl4RkROVHkzSC9SenlvCkJnd3lUdGJCNVRnWWphWmNkUHZj
            VWVJZjNlM1pVaFpmYzVFblhLU2pORjQKLS0tIG1vK1ZjUldka2EwUDhjRGhwaGxT
            ZE1KWHJpZER6Rlc1WEQ0NDUrbFFZOHcKbOQlcZtWIORzYoIAEFuZUPYS+Ta83H4z
            Z3y/OzieEgn6XnavA2VMZV4ouZxY+p1S0STKA7s7z3J8ixHz1sPyeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T17:54:44Z"
    mac: ENC[AES256_GCM,data:9Kj68TKXJon6e1b0th1ubESMP+KxmSNnWFPDT2eE7Bz273f5qSWF6+sb+1G1pWzRVpZ5BTs/sP6LlSHPVnPedzIPsVzV6IET4MjieQir1n4+4vFuTKZpTTGIUAsatDvEom5nEj0XHckXl49itUZNUx5YXuRWM2mICWarUZitPrE=,iv:3yJAUVF2bN0Ysz8hV5DiXUJ7cGfy2h5VeecWvToqltM=,tag:DTgDtRtjoMEyexcwd/xYzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: video
    namespace: default
spec:
    securityConfig: videoconfig
    commonConfig: music
    readOnly: false
    storage:
        pvc:
            spec:
                accessModes:
                    - ReadWriteOnce
                resources:
                    requests:
                        storage: 610Gi
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNmYvb09EZVNKQmE2T1o3
            Q2RyUkN2V3dRa09PdGl4RkROVHkzSC9SenlvCkJnd3lUdGJCNVRnWWphWmNkUHZj
            VWVJZjNlM1pVaFpmYzVFblhLU2pORjQKLS0tIG1vK1ZjUldka2EwUDhjRGhwaGxT
            ZE1KWHJpZER6Rlc1WEQ0NDUrbFFZOHcKbOQlcZtWIORzYoIAEFuZUPYS+Ta83H4z
            Z3y/OzieEgn6XnavA2VMZV4ouZxY+p1S0STKA7s7z3J8ixHz1sPyeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T17:54:44Z"
    mac: ENC[AES256_GCM,data:9Kj68TKXJon6e1b0th1ubESMP+KxmSNnWFPDT2eE7Bz273f5qSWF6+sb+1G1pWzRVpZ5BTs/sP6LlSHPVnPedzIPsVzV6IET4MjieQir1n4+4vFuTKZpTTGIUAsatDvEom5nEj0XHckXl49itUZNUx5YXuRWM2mICWarUZitPrE=,iv:3yJAUVF2bN0Ysz8hV5DiXUJ7cGfy2h5VeecWvToqltM=,tag:DTgDtRtjoMEyexcwd/xYzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
