apiVersion: v1
kind: Secret
metadata:
    name: videousers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:W9vrE4FS8Amhb25sdlFsVo2EA7iqOWSxAOZxJFhNxtqAZhU+lQ2KcO0Kve5pDKCDLeT2kQWJjhWBVJpw0mfxOycwZKQTLh///sZOAcW91u8ElwuQtHV8ZtwWWL9LExbOQ4cFfz3vqZNKBZfwi4SdVra6AsI/TYzRYYoy7jgTst5WOhke7E1ehFzthZS48s5om7FykVaViFzBGw==,iv:li67CgjivW6zZ0X81Ztwb7H/y0/3yfiySQYhLUV/jLw=,tag:ayLV1vbCU/pf8UQ2xfEMPg==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUGViOTkyc1JzK0l3cmpj
            bzBEVk04N1EwLzNPVzVoWUt1YzZtNjBYV0VBClRKSGR0RGNOY20xK013bkpMbXF5
            UHpqeWl4U2NEWGVxaEk3RDVZcHRtZTAKLS0tIGlYWEZWTThYU292YXB0N2dDY2Vh
            Zm55ajFlN0w0ZE1pQUhETXNqNVRSd0UKdGT8Y8ywkiX5BhwAMwcfeNax5g0EkMmr
            TeMKcshn8cGQau/3BpZ7fcVFb+ZCark0MvsF5DY/5MM7KdGsbCWtWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T09:39:58Z"
    mac: ENC[AES256_GCM,data:cnzieSCi9YHCPK6Ka3HoTwuwSMb1dsnIjz1xBBceGzOYZoy+EWGfUB5aGsH0K8ps1JgqEmDSqETsW98xUfDHWpXnkpS9Q1326ocCJCQ9hQP18jWXa0666IPeC7/MctLvu8kF+W6+tAEGdappWhhpjwHLorymRkuw9idPAf83Cas=,iv:E3K5vnG2Do30rS82iJSN0WE9GBzHi4vG42Kzk+i6GdQ=,tag:JAsuVouXiBg0gb+/cIBWDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
    name: videousers
    namespace: default
spec:
    mode: user
    users:
        secret: videousers
        key: demousers
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUGViOTkyc1JzK0l3cmpj
            bzBEVk04N1EwLzNPVzVoWUt1YzZtNjBYV0VBClRKSGR0RGNOY20xK013bkpMbXF5
            UHpqeWl4U2NEWGVxaEk3RDVZcHRtZTAKLS0tIGlYWEZWTThYU292YXB0N2dDY2Vh
            Zm55ajFlN0w0ZE1pQUhETXNqNVRSd0UKdGT8Y8ywkiX5BhwAMwcfeNax5g0EkMmr
            TeMKcshn8cGQau/3BpZ7fcVFb+ZCark0MvsF5DY/5MM7KdGsbCWtWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T09:39:58Z"
    mac: ENC[AES256_GCM,data:cnzieSCi9YHCPK6Ka3HoTwuwSMb1dsnIjz1xBBceGzOYZoy+EWGfUB5aGsH0K8ps1JgqEmDSqETsW98xUfDHWpXnkpS9Q1326ocCJCQ9hQP18jWXa0666IPeC7/MctLvu8kF+W6+tAEGdappWhhpjwHLorymRkuw9idPAf83Cas=,iv:E3K5vnG2Do30rS82iJSN0WE9GBzHi4vG42Kzk+i6GdQ=,tag:JAsuVouXiBg0gb+/cIBWDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
