apiVersion: v1
kind: Secret
metadata:
    name: videousers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:adogiHIgwySKCdGZ05NRL0Jt9gVr+J6hr7XzpToidTXY7mriZb2hfjPhOkaIXBg1FQjfG4uQJrymcOxsA4epxAJKYBiKY6687fgKALanqOtujaR/5HNqAytikaTyC9IWnI9sqYtTFsveHq1oTBoYrVt5rz0SmuOw2T/5VUj5qLRrGjVSun+PXVGdib0QSgbkBkltxrJkMzap+A==,iv:1Vh6YLS99lcBRYa/L7fkfCmt+G/z+Nf5es1xigvuH5o=,tag:Y3NLZnYcn7uNetrIwaRS/Q==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVXJ5TzlZbDQ1cGJSV3lZ
            cUFtWUtramRuUlZ2YkhWNk9NUkNnSjAzNlJZCjM3S2Z6UGZQSExyNDRVUmVJYlBY
            UG9XbDlQUGlIRXRpRkwreE91dzhPSkUKLS0tIE85akEvU1NyaUJCNHdRTzllcm42
            Smx2ZXVwcmEzRzN1T01ZM1BtSDZNV3cKL9+13R55f7Jg0Z4hjqLRIP/nPm7p4NBO
            DeZtEzW9nNbJRkLbrhnlFTWxB/JzYOfCKiOaf64kDT2/9FgvQKODZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T14:03:49Z"
    mac: ENC[AES256_GCM,data:+Q2KPACxIADR866c6FzoElCm9isbNwb3hwgHf8aSp0lfghEe1OC+08vlqL0nikzQ5xzTPay7p4pO/QOd+ncpup3ruwDDMB0ojlZ2i3w0oi7yeSO0BhHuxWUIgWoj5NGColdSst88bkD6g+d6HydqL3DlNA2qXscahFdAFCTdYTM=,iv:u4H8HW48Mo1P0dk2FWwbZ4V1zdTiU9lcAp0CY3fM2dk=,tag:j6I8twYGLWxwUmRMhrgx+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
    name: videousers
    namespace: default
spec:
    mode: user
    users:
        secret: videousers
        key: demousers
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVXJ5TzlZbDQ1cGJSV3lZ
            cUFtWUtramRuUlZ2YkhWNk9NUkNnSjAzNlJZCjM3S2Z6UGZQSExyNDRVUmVJYlBY
            UG9XbDlQUGlIRXRpRkwreE91dzhPSkUKLS0tIE85akEvU1NyaUJCNHdRTzllcm42
            Smx2ZXVwcmEzRzN1T01ZM1BtSDZNV3cKL9+13R55f7Jg0Z4hjqLRIP/nPm7p4NBO
            DeZtEzW9nNbJRkLbrhnlFTWxB/JzYOfCKiOaf64kDT2/9FgvQKODZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T14:03:49Z"
    mac: ENC[AES256_GCM,data:+Q2KPACxIADR866c6FzoElCm9isbNwb3hwgHf8aSp0lfghEe1OC+08vlqL0nikzQ5xzTPay7p4pO/QOd+ncpup3ruwDDMB0ojlZ2i3w0oi7yeSO0BhHuxWUIgWoj5NGColdSst88bkD6g+d6HydqL3DlNA2qXscahFdAFCTdYTM=,iv:u4H8HW48Mo1P0dk2FWwbZ4V1zdTiU9lcAp0CY3fM2dk=,tag:j6I8twYGLWxwUmRMhrgx+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: video
    namespace: default
spec:
    securityConfig: videousers
    commonConfig: music
    readOnly: false
    storage:
        pvc:
            spec:
                accessModes:
                    - ReadWriteOnce
                resources:
                    requests:
                        storage: 1300Gi
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVXJ5TzlZbDQ1cGJSV3lZ
            cUFtWUtramRuUlZ2YkhWNk9NUkNnSjAzNlJZCjM3S2Z6UGZQSExyNDRVUmVJYlBY
            UG9XbDlQUGlIRXRpRkwreE91dzhPSkUKLS0tIE85akEvU1NyaUJCNHdRTzllcm42
            Smx2ZXVwcmEzRzN1T01ZM1BtSDZNV3cKL9+13R55f7Jg0Z4hjqLRIP/nPm7p4NBO
            DeZtEzW9nNbJRkLbrhnlFTWxB/JzYOfCKiOaf64kDT2/9FgvQKODZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T14:03:49Z"
    mac: ENC[AES256_GCM,data:+Q2KPACxIADR866c6FzoElCm9isbNwb3hwgHf8aSp0lfghEe1OC+08vlqL0nikzQ5xzTPay7p4pO/QOd+ncpup3ruwDDMB0ojlZ2i3w0oi7yeSO0BhHuxWUIgWoj5NGColdSst88bkD6g+d6HydqL3DlNA2qXscahFdAFCTdYTM=,iv:u4H8HW48Mo1P0dk2FWwbZ4V1zdTiU9lcAp0CY3fM2dk=,tag:j6I8twYGLWxwUmRMhrgx+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
