apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: video2
    namespace: default
spec:
    securityConfig: videousers
    commonConfig: music
    readOnly: false
    storage:
        pvc:
            spec:
                accessModes:
                    - ReadWriteOnce
                resources:
                    requests:
                        storage: 1100Gi
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYmlhS0JFMWR0U0xKc1RZ
            L0lFNVN6MTR0OVdRcTBEUTJTYmNuNXArZWxjClNid0ZKMDBwNVhIcThySGl0dzlP
            M1k4cStoVDk4ZWZxY2hxYWVNeVBSdjQKLS0tIDJmZndrWFozeTdaL2MzNW5XNGJa
            QmEwT1pnTnQ2UFplVWVoK3BERFBXNFkKDuxoEzRTPCDj5tf2/YMDnHDm4I/sApSI
            1MvYtQprWBno0DA7pMtT435+pqqZHRO7/A8VIhlquAnIQDmXKKn0Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T10:12:22Z"
    mac: ENC[AES256_GCM,data:kt7tlgcl+vBGQmyKYf4LmNuNcw24k1aqA7KCVrN9FTN8BjTm3KEfu9c1h7oC+Op2iFPlD7S4jBk33nQlNMz9A9KxzCUQOzYewusE0wrWruaddhtltg07ngZSAElYZiDgmKfwSHSfVtZO9bE7BiaX0wqQ23Bp43jNfVIzFfUkCVg=,iv:Oi29Y67jtelrEurHBVcFG3LrloErbGBmB/YeDNdRG8U=,tag:FgmLCYaqHsTypxBCvcPwGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
