apiVersion: v1
kind: Secret
metadata:
    name: videousers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:cs8YLrA74dCrcsOuag9/YnqcKNC+kcqrcMAUyHbysPhPMXHRasY8QGmz4SYH50tEqjGkzbQCPGG33UpfjK1fLqdESbbBKaO2kY966t22i+B9MYZve/k/mNS980Y6QQUEvcuYNB2r4GT6P09xawXART5hn7gmrs5XRVfuunivV8xScHV88xRVjXtu9BX3Rag7DghuUzcVtFHO0A==,iv:cvwMn0A8RPMpiM29BWwgbEthh5fAu6ZcZc1t4ytYpCk=,tag:ln5nfht3dViY9g4bUes5LA==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOVpEQUFMKzEvczVFTzEx
            Z084UzVVQ3NXUjF3YXFOcGJ3K29GM0FkelVnCmRySVdTa1NOK29ubEhCNndyeEhv
            TlR0RklydXZmR3kyYW5HNmlFYVVGRkUKLS0tIGlNcGZDVDMxNzJNckZoNEhuYlhl
            bE5WeVdrMmxhM3FBYmVLc0FISzlOWkUKtxvvxkaPZTbd+qfrA8rEK1QRV1OwWxcz
            ajHYv7xuMVuEhrchLVbfVExNKR2I+FbyoRmteFVXcYI8LznWZVVW9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T10:50:11Z"
    mac: ENC[AES256_GCM,data:xHox4v9chPlarJoy2XIFLRXJ4EsMXGmeu1Tsz/H2NJe/whLMQZSYRm/tZzMAc6qYFoJAhMKE+O/GAVpKwR8ODY+vyl2uANrFNMBTDyy48u+xERpO/bU9SvpUkG5rTDISfSwl5sEjbg4bgAx1sFS6TVPYhIuI5OWM3/JqvVDFzDE=,iv:yXtRXD8PV8H44jMXFKM6RNMoTlc86QjGrWDH+Trph3I=,tag:Yoa7iUMW+MGjToZAMcVLkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
    name: videousers
    namespace: default
spec:
    mode: user
    users:
        secret: videousers
        key: demousers
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOVpEQUFMKzEvczVFTzEx
            Z084UzVVQ3NXUjF3YXFOcGJ3K29GM0FkelVnCmRySVdTa1NOK29ubEhCNndyeEhv
            TlR0RklydXZmR3kyYW5HNmlFYVVGRkUKLS0tIGlNcGZDVDMxNzJNckZoNEhuYlhl
            bE5WeVdrMmxhM3FBYmVLc0FISzlOWkUKtxvvxkaPZTbd+qfrA8rEK1QRV1OwWxcz
            ajHYv7xuMVuEhrchLVbfVExNKR2I+FbyoRmteFVXcYI8LznWZVVW9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T10:50:11Z"
    mac: ENC[AES256_GCM,data:xHox4v9chPlarJoy2XIFLRXJ4EsMXGmeu1Tsz/H2NJe/whLMQZSYRm/tZzMAc6qYFoJAhMKE+O/GAVpKwR8ODY+vyl2uANrFNMBTDyy48u+xERpO/bU9SvpUkG5rTDISfSwl5sEjbg4bgAx1sFS6TVPYhIuI5OWM3/JqvVDFzDE=,iv:yXtRXD8PV8H44jMXFKM6RNMoTlc86QjGrWDH+Trph3I=,tag:Yoa7iUMW+MGjToZAMcVLkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: video
    namespace: default
spec:
    securityConfig: videousers
    commonConfig: music
    readOnly: false
    storage:
        pvc:
            spec:
                accessModes:
                    - ReadWriteOnce
                resources:
                    requests:
                        storage: 1100Gi
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOVpEQUFMKzEvczVFTzEx
            Z084UzVVQ3NXUjF3YXFOcGJ3K29GM0FkelVnCmRySVdTa1NOK29ubEhCNndyeEhv
            TlR0RklydXZmR3kyYW5HNmlFYVVGRkUKLS0tIGlNcGZDVDMxNzJNckZoNEhuYlhl
            bE5WeVdrMmxhM3FBYmVLc0FISzlOWkUKtxvvxkaPZTbd+qfrA8rEK1QRV1OwWxcz
            ajHYv7xuMVuEhrchLVbfVExNKR2I+FbyoRmteFVXcYI8LznWZVVW9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T10:50:11Z"
    mac: ENC[AES256_GCM,data:xHox4v9chPlarJoy2XIFLRXJ4EsMXGmeu1Tsz/H2NJe/whLMQZSYRm/tZzMAc6qYFoJAhMKE+O/GAVpKwR8ODY+vyl2uANrFNMBTDyy48u+xERpO/bU9SvpUkG5rTDISfSwl5sEjbg4bgAx1sFS6TVPYhIuI5OWM3/JqvVDFzDE=,iv:yXtRXD8PV8H44jMXFKM6RNMoTlc86QjGrWDH+Trph3I=,tag:Yoa7iUMW+MGjToZAMcVLkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
