apiVersion: v1
kind: Secret
metadata:
  name: users1
  namespace: default
type: Opaque
stringData:
  demousers: |
    {
      "samba-container-config": "v0",
      "users": {
        "all_entries": [
          {
            "name": "user1",
            "password": "T0Psecre7"
          },
          {
            "name": "user2",
            "password": "L37me1N"
          }
        ]
      }
    }
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
  name: myusers
  namespace: default
spec:
  mode: user
  users:
    secret: users1
    key: demousers
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: video
    namespace: default
spec:
    securityConfig: myusers
    readOnly: false
    storage:
        pvc:
            spec:
                accessModes:
                    - ReadWriteOnce
                resources:
                    requests:
                        storage: 610Gi
