apiVersion: v1
kind: Secret
metadata:
    name: videousers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:2znC043Hd0LOUTfC2g64s9xib13RWGvRGBvshM39GorAv7Jy/6UG92rT03VL6R2m0pgCx+5+LoFQIeD4y4qJ7mL8qNbXMT5bpXONK82NO+e4RJqzLRK6mppQYa+amzISwPRFb/zJXHjkq4uGUZyHc4H79B6uR8/VyVEaVTVVjooMGKksc9RXpZj6eF6Pu99/CmAJlwc/T2R7Jg==,iv:8ZoSZuWdBiVV0EhQ2aSF5U3sPer0ugJ7Zo4/GY7YCuY=,tag:mKWfJWxuVJ9pOuHxHW2U/g==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZjVZeVdManNWZ2Nlc2Fq
            R09kWGVhbmo5czNxK2wyZDZqNUJIMjRoNUJnCklTd0FNVDgrZVBiUWFyUm1PZUlh
            TU15NU5UM1pYdzhWbzlVZUNqUUxqK3MKLS0tIFpHSHM0dnpVREYxdVlzL1NvdTFR
            YTR0aiswOXRTK1dHa3NuL0lJYWhMQWcKI90k67z1LYQJQ8XD0O8Ro7PrZXOn1phH
            5SQFkKmCX4toaLf+QnIQtHMzUPSvvDPp2N5bbpOCb2VcQi3s8gFiKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T09:30:18Z"
    mac: ENC[AES256_GCM,data:kSm1pNYd6fZdTb8O83K1uQYYV+1/wrPRQVFyuW4Z8Kfv0fcr2Cl1isJBnZT7xm/HCXVY/kV/9L0djfOaimV4/ZRZvQbbfh8lsRgF6GCMi9Vy6BvDjiMXAYQODs6RDHI3kr7kpqzn3YE5nnkAQ6kP4ip7OTPlCcRn4D41po4PCeg=,iv:lSngiWUZCN3DWME6xQjWaHDjm63VJauvSmK24B3KLtA=,tag:iQmoI+kmmt917o36d72khw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
    name: videousers
    namespace: default
spec:
    mode: user
    users:
        secret: videousers
        key: demousers
#apiVersion: samba-operator.samba.org/v1alpha1
#kind: SmbShare
#metadata:
#    name: video
#    namespace: default
#spec:
#    securityConfig: videousers
#    commonConfig: music
#    readOnly: false
#    storage:
#        pvc:
#            spec:
#                accessModes:
#                    - ReadWriteOnce
#                resources:
#                    requests:
#                        storage: 1100Gi
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZjVZeVdManNWZ2Nlc2Fq
            R09kWGVhbmo5czNxK2wyZDZqNUJIMjRoNUJnCklTd0FNVDgrZVBiUWFyUm1PZUlh
            TU15NU5UM1pYdzhWbzlVZUNqUUxqK3MKLS0tIFpHSHM0dnpVREYxdVlzL1NvdTFR
            YTR0aiswOXRTK1dHa3NuL0lJYWhMQWcKI90k67z1LYQJQ8XD0O8Ro7PrZXOn1phH
            5SQFkKmCX4toaLf+QnIQtHMzUPSvvDPp2N5bbpOCb2VcQi3s8gFiKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T09:30:18Z"
    mac: ENC[AES256_GCM,data:kSm1pNYd6fZdTb8O83K1uQYYV+1/wrPRQVFyuW4Z8Kfv0fcr2Cl1isJBnZT7xm/HCXVY/kV/9L0djfOaimV4/ZRZvQbbfh8lsRgF6GCMi9Vy6BvDjiMXAYQODs6RDHI3kr7kpqzn3YE5nnkAQ6kP4ip7OTPlCcRn4D41po4PCeg=,iv:lSngiWUZCN3DWME6xQjWaHDjm63VJauvSmK24B3KLtA=,tag:iQmoI+kmmt917o36d72khw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZjVZeVdManNWZ2Nlc2Fq
            R09kWGVhbmo5czNxK2wyZDZqNUJIMjRoNUJnCklTd0FNVDgrZVBiUWFyUm1PZUlh
            TU15NU5UM1pYdzhWbzlVZUNqUUxqK3MKLS0tIFpHSHM0dnpVREYxdVlzL1NvdTFR
            YTR0aiswOXRTK1dHa3NuL0lJYWhMQWcKI90k67z1LYQJQ8XD0O8Ro7PrZXOn1phH
            5SQFkKmCX4toaLf+QnIQtHMzUPSvvDPp2N5bbpOCb2VcQi3s8gFiKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T09:30:18Z"
    mac: ENC[AES256_GCM,data:kSm1pNYd6fZdTb8O83K1uQYYV+1/wrPRQVFyuW4Z8Kfv0fcr2Cl1isJBnZT7xm/HCXVY/kV/9L0djfOaimV4/ZRZvQbbfh8lsRgF6GCMi9Vy6BvDjiMXAYQODs6RDHI3kr7kpqzn3YE5nnkAQ6kP4ip7OTPlCcRn4D41po4PCeg=,iv:lSngiWUZCN3DWME6xQjWaHDjm63VJauvSmK24B3KLtA=,tag:iQmoI+kmmt917o36d72khw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
