apiVersion: v1
kind: Secret
metadata:
    name: videousers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:oARDk6GHSiYSmpCEEAV8etYCvb+ma4LqjwQa+y6nR3wDdkM6aPwWbdBmFiaJAhtaocN9hu8BujRdYklNv5lz/eiTrZhWXZ5trriTZkTkGMjQ1H/l9+Kr7SkcoDNfiiiqYEh6ScbQ0QdBeFlXpT8vm0fxJQpDe+EcOZ07dQ4MmWTmEBOx72x13ceAm5fKsBSHAgncjqcEXaOM1Q==,iv:XgJEI4VoUDL7bHglTw+fshfgvUEVxOnIDr4z/N0XOG8=,tag:8PL+hhAd6U0pOoohWARYlQ==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRCtJeTJWbjdTejdGRlRL
            Y0wzcnF2ZTdvRzRmT3pwOUcrMXp2U2pQUWhjClI0UmhQT0FFcUNqdU1TVGVZZ1do
            VnF1dGVrUGN6c2RjYnFPK0lyRFVRZG8KLS0tIHg0ck5VR0FvVG5qMzFma1FVNkRY
            bnNNSHhvTW5haXFSMFdOY3V4K3BHNncK+VeJ4h9+he4nOujX1BvQP8lLcM/PwwxY
            vV552f/WkIIUJgOrbLOQdnK8nedpCiAvwHeR7AeG/72tMWpNtZ0ZjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T14:10:34Z"
    mac: ENC[AES256_GCM,data:nMUE9dd4Iw+IxA43LMnXFXEYWIEihrALxP14poIYCquzE1JFzZCUiKYVprSF/0AD4LwWmiKWppsx+rxZq8KXwSGyUMRa82/hWybNQC2vz7TTjh0DSeipvxq6UPSSryP1g+tN7tRTX1um1WOj5H/T6S9W5bIJi/NYxaq7fGvzMjs=,iv:CzuJ1ZLKyqtGStAdN0Pm6STCsc/27Ro1CyH6JmMx3+E=,tag:tL3Lj7jHuZoEMjgzjj8Ggg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: video
    namespace: default
spec:
    securityConfig: videousers
    commonConfig: music
    readOnly: false
    storage:
        pvc:
            spec:
                accessModes:
                    - ReadWriteOnce
                resources:
                    requests:
                        storage: 610Gi
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRCtJeTJWbjdTejdGRlRL
            Y0wzcnF2ZTdvRzRmT3pwOUcrMXp2U2pQUWhjClI0UmhQT0FFcUNqdU1TVGVZZ1do
            VnF1dGVrUGN6c2RjYnFPK0lyRFVRZG8KLS0tIHg0ck5VR0FvVG5qMzFma1FVNkRY
            bnNNSHhvTW5haXFSMFdOY3V4K3BHNncK+VeJ4h9+he4nOujX1BvQP8lLcM/PwwxY
            vV552f/WkIIUJgOrbLOQdnK8nedpCiAvwHeR7AeG/72tMWpNtZ0ZjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T14:10:34Z"
    mac: ENC[AES256_GCM,data:nMUE9dd4Iw+IxA43LMnXFXEYWIEihrALxP14poIYCquzE1JFzZCUiKYVprSF/0AD4LwWmiKWppsx+rxZq8KXwSGyUMRa82/hWybNQC2vz7TTjh0DSeipvxq6UPSSryP1g+tN7tRTX1um1WOj5H/T6S9W5bIJi/NYxaq7fGvzMjs=,iv:CzuJ1ZLKyqtGStAdN0Pm6STCsc/27Ro1CyH6JmMx3+E=,tag:tL3Lj7jHuZoEMjgzjj8Ggg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
