apiVersion: v1
kind: Secret
metadata:
    name: videousers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:qf9mXAjaNhO7uXU2dpp5gqVNQy2Tg4VJn7szk2jCyufoscBM638wacO3Mm89HGAICzvr7o2qcF6HvuTuk5ZkE4rBJQ/aAflUZTA+81pf5mk/Zk9OIOIOBQWVxQDtZgbD1u0YY6W/BsSMOtx53zM0jvcRmMmVbQaVdKa4T3QaTai/Kc861TFmNtA2QHZq9K83tEPl7hLfl6vtTw==,iv:B3G19ksOtbW1LGtRcLz4TNovZfKDnEdOawoYcgd2bpU=,tag:U8oyywrnEt1j0BnItWJIhA==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aDdsVWNIdGI0aFJpbjNF
            SjYyMDB4SW96K3B6TXA4TDhrRFIvT0VDQ2dnCnV0czdtdVJqbTJaL2FHV29nK3Uy
            dXBBZkIxQXNvSjNxMkpYMUd2QjRBWU0KLS0tIEtZRUtmWHBiQ29Cajl5ZHVwSGhX
            UWhqN1lvcC9WYXFpUFBmZk5kN2ZrUWMKp0tEQ04zIeAcYRVzPtrCbDEalA02akDK
            E39Kyuz/FwFtrCSyLvZiP73A85gQZBUh5kMsl0ujaor/I0mIfXT9mQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-22T13:50:49Z"
    mac: ENC[AES256_GCM,data:ts1mkF4dwIh2rgG1Jkz5wtszB/bF0yG8cFOC5J6ulaQ7RLh8+2WXmvKdQgE8MOkwwqSATdQhSGnBLpdxAsu+v2weTNMR9jDSTfNBn96WYaJvxyMpL3pkA6syukMrO3vDoJEmndCUKAaKLxzKLublOJNxXbx98WwbxeqK7g7IOU8=,iv:ZkFzSdn8DJg4FFUiO/BvaDO5lNRtWGykOiqLdS9pE3Y=,tag:uSJjSrqCZhQKbL4vuvfz4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
    name: videousers
    namespace: default
spec:
    mode: user
    users:
        secret: videousers
        key: demousers
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aDdsVWNIdGI0aFJpbjNF
            SjYyMDB4SW96K3B6TXA4TDhrRFIvT0VDQ2dnCnV0czdtdVJqbTJaL2FHV29nK3Uy
            dXBBZkIxQXNvSjNxMkpYMUd2QjRBWU0KLS0tIEtZRUtmWHBiQ29Cajl5ZHVwSGhX
            UWhqN1lvcC9WYXFpUFBmZk5kN2ZrUWMKp0tEQ04zIeAcYRVzPtrCbDEalA02akDK
            E39Kyuz/FwFtrCSyLvZiP73A85gQZBUh5kMsl0ujaor/I0mIfXT9mQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-22T13:50:49Z"
    mac: ENC[AES256_GCM,data:ts1mkF4dwIh2rgG1Jkz5wtszB/bF0yG8cFOC5J6ulaQ7RLh8+2WXmvKdQgE8MOkwwqSATdQhSGnBLpdxAsu+v2weTNMR9jDSTfNBn96WYaJvxyMpL3pkA6syukMrO3vDoJEmndCUKAaKLxzKLublOJNxXbx98WwbxeqK7g7IOU8=,iv:ZkFzSdn8DJg4FFUiO/BvaDO5lNRtWGykOiqLdS9pE3Y=,tag:uSJjSrqCZhQKbL4vuvfz4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: video
    namespace: default
spec:
    securityConfig: videousers
    commonConfig: music
    readOnly: false
    storage:
        pvc:
            spec:
                accessModes:
                    - ReadWriteOnce
                resources:
                    requests:
                        storage: 650Gi
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aDdsVWNIdGI0aFJpbjNF
            SjYyMDB4SW96K3B6TXA4TDhrRFIvT0VDQ2dnCnV0czdtdVJqbTJaL2FHV29nK3Uy
            dXBBZkIxQXNvSjNxMkpYMUd2QjRBWU0KLS0tIEtZRUtmWHBiQ29Cajl5ZHVwSGhX
            UWhqN1lvcC9WYXFpUFBmZk5kN2ZrUWMKp0tEQ04zIeAcYRVzPtrCbDEalA02akDK
            E39Kyuz/FwFtrCSyLvZiP73A85gQZBUh5kMsl0ujaor/I0mIfXT9mQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-22T13:50:49Z"
    mac: ENC[AES256_GCM,data:ts1mkF4dwIh2rgG1Jkz5wtszB/bF0yG8cFOC5J6ulaQ7RLh8+2WXmvKdQgE8MOkwwqSATdQhSGnBLpdxAsu+v2weTNMR9jDSTfNBn96WYaJvxyMpL3pkA6syukMrO3vDoJEmndCUKAaKLxzKLublOJNxXbx98WwbxeqK7g7IOU8=,iv:ZkFzSdn8DJg4FFUiO/BvaDO5lNRtWGykOiqLdS9pE3Y=,tag:uSJjSrqCZhQKbL4vuvfz4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
