apiVersion: v1
kind: Secret
metadata:
    name: videousers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:+W3tcnsc4zc7YmySS1afw9INpKeSrFiBxhA7PeYIQWCXL5g2SnWnSnynICcK7LPdua7NXAWCwTuDh9tkQbogdGoJEDJiuOv/VlbF/vsUxW9j+CQ08iR6OcpWVxG1qwP3PN+SK8ugGXgsYlLnjgUblOr5JXx32htcQr28NkRadBEIiUaZOSaUe2PYZpZVEzKM4ciqhP6woOHVcQ==,iv:IE0g6OstwEXMRInRWOzCf0mHb75ODNdgDzvGV9YFUh0=,tag:qv7yNlqNoDZurxmH30Nz9w==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVEJDOXJFQXZFRllYdDR4
            RGRCQ1NDNjlITCtES3RWbW9hY092aXUwUUFnCmkreXExZ29oN0pVVC9qWEc2d2Ni
            cHZDQUNuSmRpOVJibnJNWmdiemtVQWsKLS0tIFpwVlhNUmtZd1ovWFQwT1k1NTRB
            T3R2enN4TDJnR1JwbWNDSXhsUDRNQVkKPMhzk4mXk8FGGIIYKmp6sylyGR+caM1Y
            grJ9AQK61cXdo2KtZFiSRc7rvVUOHZx4n8NO/8DMiup7HRhxpCiVzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T14:18:07Z"
    mac: ENC[AES256_GCM,data:DWFum/j4wPpYJ4cbwfbntB36nrvPTjL+Ba1PVwxmVpgJ5oDF/pT9xUjA79mGpZvREB0yvwJM3sO0wJEBXpebp1EB8CVdUjBcaCijcKB9IybzabW3QgBd7uO2k4LKxMSDQ6kQ3pImPqjn4QfzuEhUPQduVwpaf53gALK8urk3Qzg=,iv:fuq1TNTi9dG5/+OsvfDkxWilhgr6hUygLN8ReE1+/DI=,tag:FN5fq3tuLPfKtDlPA2Cnyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: video
    namespace: default
spec:
    securityConfig: videousers
    commonConfig: music
    readOnly: false
    storage:
        pvc:
            spec:
                accessModes:
                    - ReadWriteOnce
                resources:
                    requests:
                        storage: 610Gi
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVEJDOXJFQXZFRllYdDR4
            RGRCQ1NDNjlITCtES3RWbW9hY092aXUwUUFnCmkreXExZ29oN0pVVC9qWEc2d2Ni
            cHZDQUNuSmRpOVJibnJNWmdiemtVQWsKLS0tIFpwVlhNUmtZd1ovWFQwT1k1NTRB
            T3R2enN4TDJnR1JwbWNDSXhsUDRNQVkKPMhzk4mXk8FGGIIYKmp6sylyGR+caM1Y
            grJ9AQK61cXdo2KtZFiSRc7rvVUOHZx4n8NO/8DMiup7HRhxpCiVzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T14:18:07Z"
    mac: ENC[AES256_GCM,data:DWFum/j4wPpYJ4cbwfbntB36nrvPTjL+Ba1PVwxmVpgJ5oDF/pT9xUjA79mGpZvREB0yvwJM3sO0wJEBXpebp1EB8CVdUjBcaCijcKB9IybzabW3QgBd7uO2k4LKxMSDQ6kQ3pImPqjn4QfzuEhUPQduVwpaf53gALK8urk3Qzg=,iv:fuq1TNTi9dG5/+OsvfDkxWilhgr6hUygLN8ReE1+/DI=,tag:FN5fq3tuLPfKtDlPA2Cnyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
