apiVersion: v1
kind: Secret
metadata:
    name: videousers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:ZVQK1tm43Gpg/K+EtCUrpTOaiBHSEaQYL1vgYtCGDu/N1CrI4f040CQVIy4wb+5D51Kawrb5ICBZLLQQKeeQnzsvNbD/uOiOz+9dTtbu+5l+BL8cPp24RxftTpKnl5azywnimkRSneGTiptTPPiW2uh3w0exg87CMf/z0cQPY7jg8yVEBW/KjnOVYPUGmiwkNsgBovarcuhYgQ==,iv:+S3C5uKmSlHoH+eJFyfbYpoiPN8k9SUZehXnbdkaBR4=,tag:lLyVFgRN4XE7uiHm/ReAGg==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRXhqYmR3Sld3ekYwWnRl
            NXpQdS9TbG1rUDJnV3J5U1RTWUgyN0I5V0hRCjVxRDh5cG1pR2piYXUvWnRyUmUw
            TEoyTC83Ync1ek5idWJNNnZzWjNudWMKLS0tIGVzWHUvbnMwVWNldFR1bW1xRElC
            WGZLb0I0aEVPQWlHZkthaHdlOEhsMXcKwNNsQBnOkhOGUAhB0dJM4FIcwuBXvF1Z
            Oa6XkTzv51PxJvI4RCxbjbrySymXHUEOqSQJZb6jXX7NsUiJSlvVlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-10T10:51:46Z"
    mac: ENC[AES256_GCM,data:f6bSOUd6lRA72FPySN4jNRHIAwQwvgCmbmrzx0ItS9mXWRZUm1Hjg6NZNEWPuXwhm2TpWUwhHStUAFrBCK9+/RUDWPd78LTw7k4i8Sx9moBTp0SHh1vIvUNPiXJDr7O8QHrO+QjyaSZ40IDcSYgB/2PuLGyKT4/gjtTJ3seBb4w=,iv:Gq0ZST6mjHdiAdGl1Fotx+SSug8+OLxC5ozAQPpwUg0=,tag:R7g3OOBvrq9WqswH4vik8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
    name: videousers
    namespace: default
spec:
    mode: user
    users:
        secret: videousers
        key: demousers
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRXhqYmR3Sld3ekYwWnRl
            NXpQdS9TbG1rUDJnV3J5U1RTWUgyN0I5V0hRCjVxRDh5cG1pR2piYXUvWnRyUmUw
            TEoyTC83Ync1ek5idWJNNnZzWjNudWMKLS0tIGVzWHUvbnMwVWNldFR1bW1xRElC
            WGZLb0I0aEVPQWlHZkthaHdlOEhsMXcKwNNsQBnOkhOGUAhB0dJM4FIcwuBXvF1Z
            Oa6XkTzv51PxJvI4RCxbjbrySymXHUEOqSQJZb6jXX7NsUiJSlvVlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-10T10:51:46Z"
    mac: ENC[AES256_GCM,data:f6bSOUd6lRA72FPySN4jNRHIAwQwvgCmbmrzx0ItS9mXWRZUm1Hjg6NZNEWPuXwhm2TpWUwhHStUAFrBCK9+/RUDWPd78LTw7k4i8Sx9moBTp0SHh1vIvUNPiXJDr7O8QHrO+QjyaSZ40IDcSYgB/2PuLGyKT4/gjtTJ3seBb4w=,iv:Gq0ZST6mjHdiAdGl1Fotx+SSug8+OLxC5ozAQPpwUg0=,tag:R7g3OOBvrq9WqswH4vik8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: video
    namespace: default
spec:
    securityConfig: videousers
    commonConfig: music
    readOnly: false
    storage:
        pvc:
            spec:
                accessModes:
                    - ReadWriteOnce
                resources:
                    requests:
                        storage: 800Gi
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRXhqYmR3Sld3ekYwWnRl
            NXpQdS9TbG1rUDJnV3J5U1RTWUgyN0I5V0hRCjVxRDh5cG1pR2piYXUvWnRyUmUw
            TEoyTC83Ync1ek5idWJNNnZzWjNudWMKLS0tIGVzWHUvbnMwVWNldFR1bW1xRElC
            WGZLb0I0aEVPQWlHZkthaHdlOEhsMXcKwNNsQBnOkhOGUAhB0dJM4FIcwuBXvF1Z
            Oa6XkTzv51PxJvI4RCxbjbrySymXHUEOqSQJZb6jXX7NsUiJSlvVlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-10T10:51:46Z"
    mac: ENC[AES256_GCM,data:f6bSOUd6lRA72FPySN4jNRHIAwQwvgCmbmrzx0ItS9mXWRZUm1Hjg6NZNEWPuXwhm2TpWUwhHStUAFrBCK9+/RUDWPd78LTw7k4i8Sx9moBTp0SHh1vIvUNPiXJDr7O8QHrO+QjyaSZ40IDcSYgB/2PuLGyKT4/gjtTJ3seBb4w=,iv:Gq0ZST6mjHdiAdGl1Fotx+SSug8+OLxC5ozAQPpwUg0=,tag:R7g3OOBvrq9WqswH4vik8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
