apiVersion: v1
kind: Secret
metadata:
    name: videousers
    namespace: default
type: Opaque
stringData:
    demousers: ENC[AES256_GCM,data:XXfPPgoQorfZwHDjwnNReR84ABlusbp4wkBXcclhASPTpK+kHdIzLgDr4WQKapl5VA4rWLV5Of0B/LYMJfVLhECOqB0nRfjzfOUek7+uoFzmuv22e9QMsOcU1lrqMs3GBxeTqLf42bpNbQLgwHdZ4n9OoRZFUk+ONCZKL2y1IiBE8CJDFB+pPkc+O9ERVqffaIWFEJsdkLJtgw==,iv:NBEGWNLs894L78l54QQHavOKyKeMkby9fU+Y+jBFvNk=,tag:aez8FrddlE0NKR6HFGYSjQ==,type:str]
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaclhUTDFoV1QrSW9obWVl
            cUVQV2Vxa2hFeGtic2h0NkRyU3MzWVdQTDA0ClpnK0xZWjZqdDJsSEx0MWRJSlRs
            b0ovQXExemxOVFE3ZGM3WW4yYnFoc1EKLS0tIEMvMEMwYVRmWjUrU1U1MUxib1pB
            T1Y0S1Vuakh4V1RLYXJMMFhNVm1NbEkKTHtvHwfobb3XEm4lByMiybbBXm/pMqLX
            tE0Ugtw4C5V638FBkJRszXYW6muZ7BLdGBJ+tFMPF6dGBQa7oKElCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T17:52:34Z"
    mac: ENC[AES256_GCM,data:LsdMwHT/W/DCaU3gTK8CHUtnI42bvGozCckJeSMxY1zFLGOPbjVkyxyiou0L39Dzo28QKaXZv3WvEaAEasGTTgF26kaJOQodTnAqXdCU4nW6QNje2GkbPVseD4DqIhCX2nDWO/iAizDbfDERMKGqxnfOsnxTX/lLDT5jD2jOwyM=,iv:D3Ml7NLWdB6R/Z43MpJdMB6mgI4WYQHoEOT63yZ+JA8=,tag:8BWd+wXR5/Rv+wUYbIFUOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
    name: videoconfig
    namespace: videoconfig
spec:
    mode: user
    users:
        secret: videousers
        key: demousers
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaclhUTDFoV1QrSW9obWVl
            cUVQV2Vxa2hFeGtic2h0NkRyU3MzWVdQTDA0ClpnK0xZWjZqdDJsSEx0MWRJSlRs
            b0ovQXExemxOVFE3ZGM3WW4yYnFoc1EKLS0tIEMvMEMwYVRmWjUrU1U1MUxib1pB
            T1Y0S1Vuakh4V1RLYXJMMFhNVm1NbEkKTHtvHwfobb3XEm4lByMiybbBXm/pMqLX
            tE0Ugtw4C5V638FBkJRszXYW6muZ7BLdGBJ+tFMPF6dGBQa7oKElCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T17:52:34Z"
    mac: ENC[AES256_GCM,data:LsdMwHT/W/DCaU3gTK8CHUtnI42bvGozCckJeSMxY1zFLGOPbjVkyxyiou0L39Dzo28QKaXZv3WvEaAEasGTTgF26kaJOQodTnAqXdCU4nW6QNje2GkbPVseD4DqIhCX2nDWO/iAizDbfDERMKGqxnfOsnxTX/lLDT5jD2jOwyM=,iv:D3Ml7NLWdB6R/Z43MpJdMB6mgI4WYQHoEOT63yZ+JA8=,tag:8BWd+wXR5/Rv+wUYbIFUOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
    name: video
    namespace: default
spec:
    securityConfig: videoconfig
    commonConfig: music
    readOnly: false
    storage:
        pvc:
            spec:
                accessModes:
                    - ReadWriteOnce
                resources:
                    requests:
                        storage: 610Gi
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaclhUTDFoV1QrSW9obWVl
            cUVQV2Vxa2hFeGtic2h0NkRyU3MzWVdQTDA0ClpnK0xZWjZqdDJsSEx0MWRJSlRs
            b0ovQXExemxOVFE3ZGM3WW4yYnFoc1EKLS0tIEMvMEMwYVRmWjUrU1U1MUxib1pB
            T1Y0S1Vuakh4V1RLYXJMMFhNVm1NbEkKTHtvHwfobb3XEm4lByMiybbBXm/pMqLX
            tE0Ugtw4C5V638FBkJRszXYW6muZ7BLdGBJ+tFMPF6dGBQa7oKElCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T17:52:34Z"
    mac: ENC[AES256_GCM,data:LsdMwHT/W/DCaU3gTK8CHUtnI42bvGozCckJeSMxY1zFLGOPbjVkyxyiou0L39Dzo28QKaXZv3WvEaAEasGTTgF26kaJOQodTnAqXdCU4nW6QNje2GkbPVseD4DqIhCX2nDWO/iAizDbfDERMKGqxnfOsnxTX/lLDT5jD2jOwyM=,iv:D3Ml7NLWdB6R/Z43MpJdMB6mgI4WYQHoEOT63yZ+JA8=,tag:8BWd+wXR5/Rv+wUYbIFUOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
