apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb.yaml
spec:
  patches:
    - patch: |-
        apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        spec:
          template:
            metadata:
              annotations:
                kustomize.toolkit.fluxcd.io/ssa: ignore
      target:
        kind: CustomResourceDefinition
        name: bgppeers.metallb.io
