---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    tag: v0.14.8
  url: https://github.com/metallb/metallb
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: metallb-system
  sourceRef:
    kind: GitRepository
    name: metallb
  path: "./config/native"
  prune: true
  timeout: 1m
  wait: true
    patches:
      - patch: |-
          apiVersion: apiextensions.k8s.io/v1
          kind: CustomResourceDefinition
          metadata:
            name: bgppeers.metallb.io
          annotations:
              kustomize.toolkit.fluxcd.io/ssa: "Ignore"
          target:
            kind: CustomResourceDefinition
            name: bgppeers.metallb.io
