---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vertical-pod-autoscaler
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/kubernetes/autoscaler
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vertical-pod-autoscaler--vpa
  namespace: flux-system
spec:
  interval: 15m
  path: ./apps/04-controllers/vertical-pod-autoscaler/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: vertical-pod-autoscaler-admission-controller
      namespace: vpa
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vertical-pod-autoscaler--config
  namespace: flux-system
spec:
  interval: 15m
  dependsOn:
    - name: vertical-pod-autoscaler--vpa
      namespace: flux-system
  path: ./apps/04-controllers/vertical-pod-autoscaler/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
