apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: roon-extension-alarm-clock
  name: roon-extension-alarm-clock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roon-extension-alarm-clock
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: roon-extension-alarm-clock
    spec:
      hostNetwork: true
      initContainers:
      - name: cleanup-pvc
        image: busybox
        command: ["sh", "-c", "rm -rf /config/config.json && touch /config/config.json"]
        volumeMounts:
          - name: config-volume
            mountPath: /config
      - name: setup-app-data
        image: theappgineer/roon-extension-alarm-clock
        command: ["sh", "-c", "cp -r /usr/src/app/. /app-data/ 2>/dev/null; rm -rf /app-data/config.json; ln -sf /config/config.json /app-data/config.json"]
        volumeMounts:
          - name: app-data
            mountPath: /app-data
          - name: config-volume
            mountPath: /config
      containers:
      - image: theappgineer/roon-extension-alarm-clock
        name: roon-extension-alarm-clock
        env:
        - name: TZ
          value: Europe/Copenhagen
        resources: {}
        volumeMounts:
          - name: app-data
            mountPath: /usr/src/app
          - name: config-volume
            mountPath: /config
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: alarm-clock-volume-claim
        - name: app-data
          emptyDir: {}
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alarm-clock-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 128Mi
  storageClassName: longhorn
