apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns-unifi
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: external-dns
  valuesFromFile: values.yaml
