apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: default
    labels:
        app: roon-extension-ikea-tradfri
    name: roon-extension-ikea-tradfri
spec:
    replicas: 1
    selector:
        matchLabels:
            app: roon-extension-ikea-tradfri
    strategy: {}
    template:
        metadata:
            labels:
                app: roon-extension-ikea-tradfri
        spec:
            hostNetwork: true
            containers:
                - image: hassejohansen/roon-extension-ikea-tradfri:0.0.15
                  name: roon-extension-ikea-tradfri
                  resources: {}
                  volumeMounts:
                    - name: config-volume
                      mountPath: /home/node/temp
            volumes:
                - name: config-volume
                  configMap:
                    name: ikea-tradfri-config
lifecycle:
    postStart:
        exec:
            command:
                - /bin/sh
                - -c
                - cp /home/node/temp/config.json /home/node/config.json
status: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydGhiS2dJOUhFUjU1RUpm
            QWx3NVdyenpwWlh5MWJ2UUVyZTdZZjhib0RrCi9YZkc3VkVmWFJDZjg1MlUvTGlN
            Si8xZnYvYnZkK29kVWNjTWhBMU1sWVEKLS0tIHI0eWNFem12QlliSXdGTVpTRmQ5
            QTB6Vm9uM1hPUmpYN1hrYXJzc0lIM0kKTy32LNfE9Sn5J+Tva9y5/yExQXGc8BIu
            nZDDFkdr+N+TmisTVLhbuZizMhLhQaNupi9acuLPhNhJxYCWDiCHdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T13:23:12Z"
    mac: ENC[AES256_GCM,data:ZxNYxD9731xEautJ7UhmDH3GvRoy6cohvebeC+WGieJn9+bBSYV1g2w9v0eKJtRA2rrq+v4mJDqTRM1T3uMxVOkZq0cupgr8eXlmAXRHCNOv5V9EYKWplKs1xulZ1NTt8e4RhG+NLl34hSJclVfOu8vJrFwJCdljxmwcjkXJhO8=,iv:6uWN6dpM8Qi7Lda/FrVgceEV1Uq5P/PgoXCZfNVN+Ao=,tag:IpzwAh/fr1LmxChAzvvpJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: ikea-tradfri-config
    namespace: default
data:
    config.json: ENC[AES256_GCM,data:Mg+BFA157SHI4nqSMguvG7EEXUQ8sCrE4TEEIfAIO+qzXgUXN5440kuYvz8PcKMjQ5rHYfrhfjqQeaNUKFgWCwillaakMeCMul5pMrmqqTQilTa1TZ07zX7WnvXEFGmfCiTP/Xg7RiZdpt11DOM0AJY2DdSV4zdxbC9fvJtIYepcpe/rsymliBVs/2f2Xo9oS2DHkDSXoeUUSJ4B6pt6jNzhyzpqshcU+qtprCJ+MjrzJPXlx7glWy5SSWS60QENvC+mDb9BkC9+76CGtCAzC+3marKGZ1kpjDsN10KVWp1L0euNfq8yG1md3vskVyljqgmRegrqkCPxOX1g+vHGfetG2fCRC+Ewf+VDUzncJChYrLxGyiVf/d2LsqzGX3a67ah/E4Vxxfz6TFYLpR/wWrSMILa+KUs708qJCBArF4R3m0X6dPmh8FXw8qDDWy4DXXiiDfPxY5QVGPFzV3S/gAGnB2MP6/f1VokphuDbCm/y8RidfIuuN05sEcY3PNZLzRsWeWwSKsmWYrnT3f/79ouqfRCKquDQNGdqilaw+/pDxaInP76tUTcN0G3McX+/XUruODGTv5Lvx3GFtUhZj6tqMk/Le8XS8+SyoRnHLTTsnAOAO3A44QrXfvkXfJfapR5AKnOKbp1MM53CllgEsicRE25P1CUfq04Y0w25XUM5mcciAF4ICeCEghu5YQE=,iv:oATBsHQYU9WJjuEQ7+JlIXcWoeum6a0QM8Wjf0qErog=,tag:c5NHCAjVCfcb54hSjNh3xg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydGhiS2dJOUhFUjU1RUpm
            QWx3NVdyenpwWlh5MWJ2UUVyZTdZZjhib0RrCi9YZkc3VkVmWFJDZjg1MlUvTGlN
            Si8xZnYvYnZkK29kVWNjTWhBMU1sWVEKLS0tIHI0eWNFem12QlliSXdGTVpTRmQ5
            QTB6Vm9uM1hPUmpYN1hrYXJzc0lIM0kKTy32LNfE9Sn5J+Tva9y5/yExQXGc8BIu
            nZDDFkdr+N+TmisTVLhbuZizMhLhQaNupi9acuLPhNhJxYCWDiCHdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T13:23:12Z"
    mac: ENC[AES256_GCM,data:ZxNYxD9731xEautJ7UhmDH3GvRoy6cohvebeC+WGieJn9+bBSYV1g2w9v0eKJtRA2rrq+v4mJDqTRM1T3uMxVOkZq0cupgr8eXlmAXRHCNOv5V9EYKWplKs1xulZ1NTt8e4RhG+NLl34hSJclVfOu8vJrFwJCdljxmwcjkXJhO8=,iv:6uWN6dpM8Qi7Lda/FrVgceEV1Uq5P/PgoXCZfNVN+Ao=,tag:IpzwAh/fr1LmxChAzvvpJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
