apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: default
    labels:
        app: roon-extension-ikea-tradfri
    name: roon-extension-ikea-tradfri
spec:
    replicas: 1
    selector:
        matchLabels:
            app: roon-extension-ikea-tradfri
    strategy: {}
    template:
        metadata:
            labels:
                app: roon-extension-ikea-tradfri
        spec:
            hostNetwork: true
            containers:
                - image: hassejohansen/roon-extension-ikea-tradfri:0.0.15
                  name: roon-extension-ikea-tradfri
                  command:
                    - /bin/sh
                    - -c
                    - cp /home/node/temp/config.json /home/node/config.json
                    - '&&'
                    - node .
                  resources: {}
                  volumeMounts:
                    - name: config-volume
                      mountPath: /home/node/temp
            volumes:
                - name: config-volume
                  configMap:
                    name: ikea-tradfri-config
status: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNy9HSFBlQmJLV0VCQ2po
            QytyTnBmOUpvdFZENUJmMDJLaFVhREdOWFNBCmF2VnBxc210N1NBNkZBZURqQnNT
            ck5Kd0YrMm82T3pDbnkyQ0U2SUZGRzQKLS0tIE00ZUNyc0JEUlNCenh6Yk9lcVVH
            Wk40cTJlSXJSRStVNUFmdXpHRFBsTHMKBTFefqVugSfrKnVW48aak56AXVl0NbcU
            zJGjjhVzeLpJHSfMA1GGz1/jGZdO8QIYdPsIi7nCQpzxjPFFg0dTew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T13:40:24Z"
    mac: ENC[AES256_GCM,data:Vu0knN6dMcJDoOiZiiYJp1w6FepiIjn+vjoLt6ajwCj5itgNUzYHeyCiF+V5L9m7OSgnuKZFcYsYWQeq95tBGCT2QoFEDE44uxSZGzF5HBDpCUIt936yOF7wT3nyNC+4Q1cQzxFvL8KPviFyAYAc2PJLrP7fqyXAWRZioakomgE=,iv:TbGGcXayVjXePlrUgg7G2cF77O9lrNj/cEia5EIx6f8=,tag:+oTD1SdRz1R60YgIVO8q2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: ikea-tradfri-config
    namespace: default
data:
    config.json: ENC[AES256_GCM,data:E+sgGBSf53085QjcCnprmB1NVOAAFwvhyp/ohbyeWl9psuLV77pFaOYj+Hd7LcqoshQr7kgfMqexDoAZAGGDeCGBqLmhT5dTBCewnFjPDeTvxqNoVPtrl6/bTvgqSt9ZJir5sfM2UOsOu5BpbALDjWMBEIiqz4kniQxqHckeFDKy+BJ8BK8cCMAxrcZQu2RMzfeGW35TBJ4+wfrSC6X2OZqOHwto8oPX4rkDIibMB4oqIOoEVvwNjqIElLl1+HGM416XWdYInAOoAONSWc1CguXe8V+gkIF4T0mC20mNXB4qBM/r9XSApcgm79X8Yk5U05xdVTslTwa8ZMdIqyNfwT+cifyDiw8r6kEXggvda1SIAY3AqgJjjTc89mP6+fXFYc+TtpxcOCfFeJROaF82U2T5oue8d4yPgv8Kra+I8V36Fe5gEV1OK47CuZcZ60xQAjoaNkHlKTb1a8HTCqKOtM/tPu9jkksb+pNCDm/c6l/MlKMzhbI4rRYBRQjxwjdmBkgURc1ndBpOJxilS8V4LjZUN5cIatnEmbexHi+5eMsQC7aRaHBpeUvLBvI0myIz85JDBkuAMzvmS5wGUgY+zDiRzZpndyRLSzgr3hUYtMqSmc7kbUmlW1tozzsjVLovHUCYXcsQG0tPMxad9TUbMderF5bKTXo0Xn5XdUXDt447KZrTQLbhrvuxAKqGTWc=,iv:H7ci3CFDt6lCOThtPzYvFJ+z02CEknchIUMo//slDpM=,tag:frPn0VYJLcdtTwRZqyAp1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNy9HSFBlQmJLV0VCQ2po
            QytyTnBmOUpvdFZENUJmMDJLaFVhREdOWFNBCmF2VnBxc210N1NBNkZBZURqQnNT
            ck5Kd0YrMm82T3pDbnkyQ0U2SUZGRzQKLS0tIE00ZUNyc0JEUlNCenh6Yk9lcVVH
            Wk40cTJlSXJSRStVNUFmdXpHRFBsTHMKBTFefqVugSfrKnVW48aak56AXVl0NbcU
            zJGjjhVzeLpJHSfMA1GGz1/jGZdO8QIYdPsIi7nCQpzxjPFFg0dTew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T13:40:24Z"
    mac: ENC[AES256_GCM,data:Vu0knN6dMcJDoOiZiiYJp1w6FepiIjn+vjoLt6ajwCj5itgNUzYHeyCiF+V5L9m7OSgnuKZFcYsYWQeq95tBGCT2QoFEDE44uxSZGzF5HBDpCUIt936yOF7wT3nyNC+4Q1cQzxFvL8KPviFyAYAc2PJLrP7fqyXAWRZioakomgE=,iv:TbGGcXayVjXePlrUgg7G2cF77O9lrNj/cEia5EIx6f8=,tag:+oTD1SdRz1R60YgIVO8q2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
