apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: default
    labels:
        app: roon-extension-ikea-tradfri
    name: roon-extension-ikea-tradfri
spec:
    replicas: 1
    selector:
        matchLabels:
            app: roon-extension-ikea-tradfri
    strategy: {}
    template:
        metadata:
            labels:
                app: roon-extension-ikea-tradfri
        spec:
            hostNetwork: true
            containers:
                - image: hassejohansen/roon-extension-ikea-tradfri:0.0.15
                  name: roon-extension-ikea-tradfri
                  resources: {}
                  volumeMounts:
                    - name: config-volume
                      mountPath: /home/node
            volumes:
                - name: config-volume
                  configMap:
                    name: ikea-tradfri-config
status: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0S3RmcU84RTAyTmpKWVZh
            K2Q4Tmt6YjhZZE8xNTBDdFZFWFZ4K3FjVWowCjEzTW54MjJSY1RuR3ZkaVlRTDVo
            dHN2eVFxVy9jaUVySi9pTjJ4VnFsalEKLS0tIGFVYWZCU0pUMzdVZmFJM2V2cGZX
            U3hIeGZZcjlJR2gwZktrQnkwRXZpaWsKwkTAQHsMMUcxsTho8j/1hs3w2JSS2EEX
            DDrqUGFJ/X8C/iTKk3vd2bQDlUd7tmTMEbk7vz5cOZ7vzTHAL58VRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T13:11:37Z"
    mac: ENC[AES256_GCM,data:yLfbVC/g6vlgji+hk66dH6yWFsQiT99GjxdqIlDE8MvExnnZHhaytf7qz6sZeinBa+qK7DAB2ufwiVH2ZtpjbPqKqNvCVO2FoxPVVpqKjt5jsW2ytUZRKnVYuqiw4dFdzB3hYi2Lo2WoCeUMLb6mI+tXOwin5MYgBhx+oQUf89w=,iv:Lni1At7eCn/0G1SG8zE0UbD7ZLOL7Y/gt8P59nGXfv8=,tag:UH9PcWd7qb3iT2ndqPVY8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: ikea-tradfri-config
data:
    config.json: ENC[AES256_GCM,data:WukBKf48Dcvka1KiuScFCvSBix7EgwwRNkcIuEYPPF1c+EmDG4KMEAA3ToISsuV/z8zCSWD6NZfyvWY4+UwUMiKrKKEir1R8rv0iDFaMzjbdmETiyE6ncqlsgbr4WXppnJPkChIBEUmieQSPeE7usOHVza7xppDAoXdjkbpY9sZb26kY2WSULv+0Hup5s7PEEgI/PlhcLl5wYewWxmnGiEZ4Cm6uHsJvlej6a6uYIfMFBHJH2mJ2FHj6D7lbjoYs3HDQ1eWn39EeQ94TCBUgMziccF4KDS8Swl0N60ZRRNPdTMPMbtrDHP2l6mI9z0ksvMoMYu8bBjqgH/7TodQzUwI7X1IOkoq/WrogJFqe4zy+ivHjlQU2ROrBaJGRyefM/TiaMZPxlSBBfRbms8nJINZcy6tZ5yzxwMMltVi3JmUDYElR+uiEZtnGM/tTTjpE6meGPeXoCfxYNhLlxiFvR7xp30RNK5Bv/ezgzIz9saB6srmr+MisMnmNVy3YJISfPcacqe66owtUbX0Cqz/Gq4qAw22+eujq3m/M4bJLRfLHDU8SbZvr61BpfRYhNZHIF8vtp6vktWxEdXybh725s6i7FWubnvTpnSLOXNvPbJRhiPCiohnYWSc8jRtRP3b3a6xA2/fgZCOAyRMqrAThv3KHQ4jYL+SM2PnNAGdKrsPtKVnD6Q68SiZlgYV13fk=,iv:Fa6nsyKaBD9ymomuXsOCEDiLhkShkJEQNDCJDtBD+BE=,tag:7GbiaFGAcJHbMe5Fz0L5Jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0S3RmcU84RTAyTmpKWVZh
            K2Q4Tmt6YjhZZE8xNTBDdFZFWFZ4K3FjVWowCjEzTW54MjJSY1RuR3ZkaVlRTDVo
            dHN2eVFxVy9jaUVySi9pTjJ4VnFsalEKLS0tIGFVYWZCU0pUMzdVZmFJM2V2cGZX
            U3hIeGZZcjlJR2gwZktrQnkwRXZpaWsKwkTAQHsMMUcxsTho8j/1hs3w2JSS2EEX
            DDrqUGFJ/X8C/iTKk3vd2bQDlUd7tmTMEbk7vz5cOZ7vzTHAL58VRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T13:11:37Z"
    mac: ENC[AES256_GCM,data:yLfbVC/g6vlgji+hk66dH6yWFsQiT99GjxdqIlDE8MvExnnZHhaytf7qz6sZeinBa+qK7DAB2ufwiVH2ZtpjbPqKqNvCVO2FoxPVVpqKjt5jsW2ytUZRKnVYuqiw4dFdzB3hYi2Lo2WoCeUMLb6mI+tXOwin5MYgBhx+oQUf89w=,iv:Lni1At7eCn/0G1SG8zE0UbD7ZLOL7Y/gt8P59nGXfv8=,tag:UH9PcWd7qb3iT2ndqPVY8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
