apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbCommonConfig
metadata:
    name: video
    namespace: default
spec:
    network:
        publish: external
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
  name: video
spec:
  commonConfig: video
  storage:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 610Gi
  readOnly: false
~
