---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: 1.10.1
  interval: 10m0s
  values:
    longhornUI:
      ingress:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: longhorn.k8s.1mx.dk.
    service:
      ui:
        type: LoadBalancer
    defaultSettings:
      backupTarget: s3://1mx.dk-longhorn-backup@eu-central-2/
      backupTargetCredentialSecret: wasabi-longhorn-secret
      defaultReplicaCount: 2
      createDefaultDiskLabeledNodes: true
    metrics:
      serviceMonitor:
        # -- Setting that allows the creation of a [Prometheus Operator](https://prometheus-operator.dev/) ServiceMonitor resource for Longhorn Manager components.
        enabled: true
        additionalLabels:
          release:  prometheus-release
