apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:yOY0geT7YoZUxn521QTThCMWbFLB2XaKk9/02Q==,iv:6vwIVTAeCbk/D6p5bL63NUuQcWLD8Z7ymG1FxJpuTGQ=,tag:e6bOXmTLGIAj5clT7UY2Xg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:jWmDhQpjYhyh1tsz9ZEYZr0QA5V5ZeJcHSSjkYPsLTJx1OPKhm0t0L51j9FMSDHK,iv:cOxG34XyuakDldlOg9sx4N9JA076oOwRMPHJJ+q5c98=,tag:NGG/HYLj9zd8ZG5cVc3Sxg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fazg891a2lNqbEjrxF49MsVYQpnfk9O5ayL/0RwKK3D+NezQpjlOtnl28QEMX9P7X/BJDT4mOX4=,iv:xUU0XQ/UNKf2fv8WcUwzIKLq9CheBBAtbapzivi6w7k=,tag:jLbnDkMApuoRaczDehhzKA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:nnXPL9EDy+e+YkTGTI6k9g==,iv:dXE3gBxsfFaqjPskWny6lvcVXbPRvMQ7I5YppC1Mjs4=,tag:ZHJd8vV7x74WBCrhvN6iPA==,type:str]
kind: Secret
metadata:
    name: idrive-longhorn-secret
    namespace: longhorn-system
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRmkzOVY4b2hoSWNNZURW
            eGwrVjV5eWZrWHdkNUdaRzVrbmNBVEFGYm53CkNyQTcrYWZyenhxMWdkbFNBckEz
            K0M3V2Y1UVFrUnVJTHBsNUNJTU5xb3cKLS0tIGgwN1dxWFM1dGpaS29vNFBHS2w2
            dDM1MDJxSDVoZWlBd0FvdzU5RGZvUDAKCYUf4wf6IgAkGpS8CpiJpwk5NMfd2EqL
            p/igjoWmiB0JcmlPY5mAOwsPVeqJmdOL7OVKenLM7ocT9nyo0CumfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T07:52:00Z"
    mac: ENC[AES256_GCM,data:Q+IVIlDnergQp6Bc/Ey51rDBdoup/2hnr5hGQ2wKpkfZhiaXOpe2T6fUiSKo9xQKr00wHNx4wCIdYxcNee8oQ82MsbwiNmUIfugk6Wwug1fMt5tzt3w6mYjHv10CWBrjgdxB6sP1fckuxvDTciCneMXELJi4rC5k1AtWc66J12Q=,iv:gKXbsZgMJoNAAeJYkVqrfmNKTSmsTHm1E8krnQM+m0Y=,tag:oVsbiWp+aYATvFopqHKY2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
