apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VaUhJF8rZgz8x4d3L1IFBShgrTs=,iv:tEyi1/DnbOL25WeTQSrKbovmuFPS43Vrtwmgukt1IdE=,tag:X3lHeSosnbhdSz7iMXsy9A==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:HXrGiT1IaYRQo32rLuljTsZKHY3Qz8RTFdOWhg==,iv:HcDvqTOj5KK+BXMcJMARahWuiwDTFLfvrTvPx+yXyr8=,tag:cNIDvIhp+YDC8vynHNUNZw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+Mkz3478GkNadpEvpD2+QATdOWdtE9JjXdSddri3Zt9Ne0ojfg+/Qg==,iv:UqMwgxPDeFtxbtq5CLactUzle7DNpBGcPttWUBpxYI4=,tag:eXnJPRidvFH+8IEl76wUHw==,type:str]
kind: Secret
metadata:
    name: idrive-longhorn-secret
    namespace: longhorn-system
sops:
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eFdHOUZnZ3lrS1dEdGFG
            NmdCMTdGSFh2YnN5WTMwaExwZXE4cmZYYTBVCjJYLzRvaVpEbHNWSDhIWXdlKzMy
            N2E4SzFVU0R2cWE5NzgrbUJZSFNTRnMKLS0tIC9oOWhkRUFVdUFZZ3NMakNQNmhY
            NlNOVk1CT1FMcnFibHZPT1QyS1NlbTgKPhz2PfohAPN9bXLiMJi+ipewzyVQxz3J
            cR6km3ZYSSS20Apm1nt7Tp+r4huz1VnWYuaZuLLjWtfpPz3pc1Xy1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T16:01:35Z"
    mac: ENC[AES256_GCM,data:C12Oxm8D+yZ7MV2S/j607drqJiRSpje0YEKPmEPV0bCt9yER6aUKry5pEpBAHTIAhADiDt9odgixq/z9pnyHxLJCgdrMsLOmJyEeLrsV5+S+pXryZJ5aMvAbqqI9HlmV/xBEmJZyk31TL3lvL4PknkMXX0jv7WOU2gPIVrPEywQ=,iv:Oz3cnXwYKwa6Xpbc2ICJCVPap4Wbt125xYObjwSTeNs=,tag:oHsU2WFGwxJTe4NO0WLcaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
