apiVersion: v1
kind: Secret
metadata:
    name: wasabi-longhorn-secret
    namespace: longhorn
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:s6i45/7ys2Q2TfItq8u6a8y+krQ=,iv:qxAKaXDFOn5AFvmkKxmxpwmGQsooTXKUBotX7Ck1z4Y=,tag:0Z3yicYTdxQprHM041m0BQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ExKs9U75ooCqvh7QIEQgUoBzlgHbZG4FNALi8Bae0+65eQPOQBhuTw==,iv:T7kCx/d0cexGfni9btN8SN3+OAJVluTXYO6W1VeusPQ=,tag:oGDPicy7n6ISXhmlk1bMFg==,type:str]
    AWS_ENDPOINTS: ['https://s3.eu-central-2.wasabisys.com']
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTmVNUmxrb2ZXZ2Q3d1pK
            NE5hMnNpZjA1RGtSSVRoV0EweTFSU0xtMWt3Clozd2YxSGJxME5iN2lrL2liUUNu
            RDlOQ2RUa3ZMWkp6bng4dHNHRFo1VVUKLS0tIDFLa00zMmdnNkhnMlVTbDNyazB4
            Vnp4SW9naGwvZUVaSS9qejJmUVJ0Q1UKZXoUY1X5ITGq1cpA0WBaV/I1cpzDt0Dr
            3A5TB4t3uCOCixtS7gVsVNT/Co0Jc0O/EtWDxMRJSwOupZd+E2Lptg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-25T13:57:26Z"
    mac: ENC[AES256_GCM,data:R82cGWAg5uSy8d5CxZ7DvxFHVD0XSSdXAZ352y3OaW+QSJpbF/XL/rLFpxvj9fduyR9QXxtgLakGYpamVtRNpZdK4un+j8xQkC3VJbScK93YHqoVs+ujcd7F384EBUN4RhHlRJdLa3oqVN2+gAaYD0Sn7RjKgZccquENjSWjf1k=,iv:ar2iNZjH8bXnU+oCSusOQ9ZEblAcwh7atI3ITuSc+4s=,tag:76ah657taFSUkNfOQ4zlNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
