apiVersion: v1
kind: Secret
metadata:
    name: wasabi-longhorn-secret
    namespace: longhorn
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JRgQE3eDcqIe1dq3N1d4jhIpr6s=,iv:4wOkJFVabfccyumnr6BNhkqzyUIlN0SUDsWm1+zT6JM=,tag:vCBxOgzZ6K6ocmlZigXxlA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:O0U0k3LxqbsksgXtuqF8Fo4bpYpF7FP7wixoGbuqi6rGw5CAr/dupA==,iv:96sQnkC565gGmpHywZra1vNqDWmgDyP82+yedVEUjgg=,tag:OOD/db5R+q+0/cWPdKEkhg==,type:str]
    AWS_ENDPOINTS:
        - ENC[AES256_GCM,data:dqrEqQKlG4fynq/0e1qMvjTjil6NMmvnYQX0vQsSE811zP+gxQ==,iv:gS7LvveGfAEvLJQmvc2NSYysx1aS0APptHM3hiRsQpA=,tag:Ubvaz80IMaq8Y6kIrT50iA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSFRZRHExb0JuWG1oZStS
            MlBtQ1NTdHFidVJjaTdzTUZKaFpwa2E3OVJjCkpaU3phL2UyMjkzUmExai8vc0hq
            OEhFR0ZuR0tPWm40NlZKY0FlelNETmsKLS0tIDFpSmhPejc4UWxqWmdHYzY2R2NV
            TjMwVkNiZVVDZEE4SnRrYzRhVUJnQWcKEIayvW+L/GjU32/flFAv5dwqJoC5XugR
            oZo+4IntEGngCJ+IIbaByhV8EkE0pRVBkgwYDFQDWkD0/w3TZx+c1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-25T16:59:55Z"
    mac: ENC[AES256_GCM,data:X5ljLGG6sBcOboZtprTQTxWGzIs4w/ypNvoLRxRP9jlBUlmky5aA6s+ROaTDlscMpeBtKSPyB7VvlfjuVqseT6UAQlT7JUm9/Vs5YxQbMN01ixBtGzdm89iKQYaYXK5w7U5quSqL21rJDt+SYoImRNxAY4AJ+CaWVRmp2VzBk2o=,iv:tbnM30iGkWqBopqAbO3/stUNuQwin6IyILc/Fa/NRpY=,tag:sJdP6duTdGjaNsuWQbr6Lg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
