apiVersion: v1
kind: Secret
metadata:
    name: wasabi-longhorn-secret
    namespace: longhorn-system
type: Opaque
data:
    dummy: ENC[AES256_GCM,data:+W+EbMyLSe8=,iv:FmN16nUJSh5iz/NB/sgmdUObMRts1yJE42/2XaT4K38=,tag:a9kLNo/ijVRe6u4XSu262Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k4pr9evth7r8f6dajz6jee945582dklr72mklj9gpwcvnxkgc5asruclml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOUdVYVFLcWxvYzdOdlVq
            VWF3MXU5K015Rkl6cWw1Yy9vNnkyOXpqOEhjCnNHMWVTUWJSZ1I3b3JWbEpuNlVG
            VGxVM2p2NjRDSUo0bGQxODYzUW56dk0KLS0tIGNuckZTZlN1bUhpTitZZVhRbnJu
            Q2lxZm55SWdzeC95ZTZCOXVCNUVZdXcKadyuEPkx8pqwIurZnFkIjo5xec1m6nGT
            koXRHS4j8niV8rdtYQm+AeBacwWmOAJXgVzV+fhDCTfV9YRtMTa0zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-25T18:15:55Z"
    mac: ENC[AES256_GCM,data:NOuQRfTVhcbkYy6ASpD2yMEPPingmoJwo0A87mxVwwYgrNyXulCeGWRoVIZCfkL8OQhANM386HucJSqZ2sAPJaugCDeUby6z/tXrTyMkDfA4r4fCuyNUy2vnMgNgFn+nXiRTYS+I6uHpqK80u0pHagnEWLpqD7BmcoV6rkdDlog=,iv:PPDkW8UtocTnikrhUEWYTVYusUueqE6AA6fDzldl3fU=,tag:Y1UWrIqcRAzBwOBHSRYfhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
