---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: samba-operator
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    tag: 7a96dbc17391a0eaff6d6a7263cfe058b0377fc9
  url: https://github.com/samba-in-kubernetes/samba-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: samba-operator
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: samba-operator
  path: "./config/default"
  prune: true
  wait: true
  timeout: 3m0s
