---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-kyverno
  namespace: flux-system
spec:
  interval: 30m
  path: "./clusters/minis/apps/policy/kyverno/kyverno/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-kyverno-policies
  namespace: flux-system
spec:
  interval: 30m
  path: "./clusters/minis/apps/policy/kyverno/kyverno/policies"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: cluster-apps-kyverno
