---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-release
  namespace: monitoring
spec:
  chart:
    spec:
      chart: prometheus
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-repo
  interval: 1m0s
  values:
    service:
      type: LoadBalancer
      externalIPs: ["192.168.8.13","192.168.8.14","192.168.8.15","192.168.8.16","192.168.8.17"]
