---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-repo
  namespace: monitoring
spec:
  interval: 5m
  url: https://prometheus-community.github.io/helm-charts

