---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-repo
  namespace: monitoring
spec:
  interval: 5m
  url: https://github.com/grafana/helm-charts/tree/main/charts/grafana

