---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 30m
  chart:
    spec:
      chart: kyverno
      version: 3.2.0-alpha.1
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
      interval: 30m
  values:
    backgroundController:
      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - ""
              resources:
                - nodes
              verbs:
                - create
                - update
                - patch
                - delete
                - get
                - list
                 #    postRenderers:
                 #    - kustomize:
                 #        patches:
                 #          - patch: |-
                 #              apiVersion: v1
                 #              kind: ConfigMap
                 #              meta-data:
                 #                annotations:
                 #                  gylle: gylle
                 #            target:
                 #              apiVersion: v1
                 #              kind: ConfigMap
                 #              name: "kyverno"
                 #              namespace: "kyverno"
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: ConfigMap
              name: kyverno
            patch: |-
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: not-used
                namespace: not-used
                annotations:
                  gylle: 'gylle'
