---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 30m
  chart:
    spec:
      chart: kyverno
      version: 3.2.0-alpha.1
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
      interval: 30m
  values:
    backgroundController:
      serviceMonitor:
        enabled: true

      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - ""
              resources:
                - nodes
              verbs:
                - create
                - update
                - patch
                - delete
                - get
                - list

    admissionController:
      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - ""
              resources:
                - nodes
              verbs:
                - create
                - update
                - delete
