# ztunnel.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  interval: 10m
  chart:
    spec:
      chart: ztunnel
      version: "1.30.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    namespace: istio-system
    hub: "docker.io/istio"  # Explicitly set the hub
    tag: "1.30.0"           # Explicitly set the tag
    image: "ztunnel"       # Explicitly set the image name
    podAnnotations:
      sidecar.istio.io/inject: "false"  # Disable sidecar injection
