apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: l2pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.8.10-192.168.8.50
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - l2pool
